/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarquesIndexRouteImport } from './routes/marques.index'
import { Route as MarquesBrandRouteImport } from './routes/marques.$brand'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarquesIndexRoute = MarquesIndexRouteImport.update({
  id: '/marques/',
  path: '/marques/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarquesBrandRoute = MarquesBrandRouteImport.update({
  id: '/marques/$brand',
  path: '/marques/$brand',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marques/$brand': typeof MarquesBrandRoute
  '/marques/': typeof MarquesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marques/$brand': typeof MarquesBrandRoute
  '/marques': typeof MarquesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marques/$brand': typeof MarquesBrandRoute
  '/marques/': typeof MarquesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/marques/$brand' | '/marques/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/marques/$brand' | '/marques'
  id: '__root__' | '/' | '/marques/$brand' | '/marques/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarquesBrandRoute: typeof MarquesBrandRoute
  MarquesIndexRoute: typeof MarquesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marques/': {
      id: '/marques/'
      path: '/marques'
      fullPath: '/marques/'
      preLoaderRoute: typeof MarquesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marques/$brand': {
      id: '/marques/$brand'
      path: '/marques/$brand'
      fullPath: '/marques/$brand'
      preLoaderRoute: typeof MarquesBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarquesBrandRoute: MarquesBrandRoute,
  MarquesIndexRoute: MarquesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
