const wrap=(title,intro,badge,body,aside)=>`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · <a href="/accessoires/">Accessoires</a> · ${title}</div><span class="eyebrow">${badge}</span><h1>${title}</h1><p>${intro}</p></div></section><div class="container template-grid accessory-layout"><article class="content-main">${body}</article><aside><div class="sidebar-card"><span class="eyebrow">Repères</span>${aside}</div></aside></div>`;

export const accessoryHub={
 title:'Accessoires et pièces pour cafetière italienne',
 description:'Adaptateur induction, joint, filtre et pièces Bialetti : identifiez l’accessoire compatible avec votre modèle et sa taille.',
 canonical:'/accessoires/',
 body:`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · Accessoires</div><span class="eyebrow">Compatibilité avant achat</span><h1>Accessoires et pièces pour cafetière italienne</h1><p>Un joint ou un filtre n’est pas universel. Commencez par identifier votre modèle, sa taille et parfois sa génération avant de commander une pièce.</p></div></section><section class="section"><div class="container directory"><a href="/accessoires/adaptateur-induction-cafetiere-italienne/">Adaptateur induction <span>→</span></a><a href="/accessoires/joint-cafetiere-italienne/">Joint de cafetière italienne <span>→</span></a><a href="/accessoires/filtre-cafetiere-italienne/">Filtre de cafetière italienne <span>→</span></a><a href="/accessoires/pieces-detachees-bialetti/">Pièces détachées Bialetti <span>→</span></a></div></section>`
};

export const accessoryPages={
 'adaptateur-induction-cafetiere-italienne':{
  title:'Adaptateur induction pour cafetière italienne : quand l’utiliser ?',
  description:'Plaque adaptatrice induction pour moka : compatibilité, diamètre, sécurité et alternative d’une cafetière nativement induction.',
  canonical:'/accessoires/adaptateur-induction-cafetiere-italienne/',
  body:wrap('Adaptateur induction pour cafetière italienne : quand l’utiliser ?','Une plaque adaptatrice permet de conserver une moka aluminium sur induction, mais elle ajoute une interface chauffante et des règles de sécurité.','Accessoire · Induction',`
<section class="guide-answer"><span class="eyebrow">Réponse courte</span><h2>L’adaptateur est surtout utile pour conserver une moka aluminium que vous possédez déjà</h2><p>La plaque Bialetti officielle mesure <strong>13 cm</strong>, est fabriquée en acier et permet d’utiliser une cafetière aluminium sur une plaque induction. La fiche actuelle la donne pour les Moka Express jusqu’à <strong>6 tasses</strong>.</p><p>Pour un nouvel achat, comparez ce choix avec une moka nativement induction : Venus, Moka Induction ou Brikka Induction évitent la plaque intermédiaire.</p></section>
<section><h2>Comment l’utiliser sans surchauffer</h2><ol class="decision-list"><li>Posez la plaque adaptatrice sur la zone induction.</li><li>Placez dessus la cafetière déjà préparée.</li><li>Utilisez une puissance moyenne, pas la puissance maximale.</li><li>Quand le café est prêt, coupez la plaque et retirez la cafetière.</li><li>Laissez l’adaptateur refroidir sur une surface adaptée : sa base devient très chaude.</li></ol><div class="guide-callout"><strong>À ne pas faire :</strong> préchauffer la plaque seule. Bialetti déconseille explicitement son utilisation sans charge, car elle peut surchauffer.</div></section>
<section><h2>Adaptateur ou moka induction ?</h2><div class="guide-split"><div><h3>Gardez l’adaptateur si…</h3><p>vous possédez déjà une Moka Express aluminium en bon état, dans une taille compatible, et souhaitez continuer à l’utiliser.</p></div><div><h3>Préférez une moka induction si…</h3><p>vous achetez aujourd’hui votre cafetière principale ou voulez éviter une pièce supplémentaire à chauffer, manipuler et ranger.</p></div></div><p><a class="text-link" href="/comparatifs/cafetiere-italienne-induction/">Comparer les moka induction</a> · <a class="text-link" href="/guides/cafetiere-italienne-induction-compatibilite/">Comprendre la compatibilité induction</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/bialetti-induction-plate">Bialetti — Induction Plate 13 cm</a></li><li><a href="https://www.bialetti.co.nz/products/moka-express">Bialetti — alternatives induction à la Moka Express classique</a></li></ul></section>`,`<h3>Repère</h3><p>Plaque Bialetti 13 cm, jusqu’à 6 tasses sur la fiche actuelle, puissance moyenne uniquement.</p><span class="pill">13 cm</span><span class="pill">Sécurité</span>`)
 },
 'joint-cafetiere-italienne':{
  title:'Joint de cafetière italienne : comment choisir la bonne taille ?',
  description:'Choisissez le bon joint de moka selon le modèle, la taille et parfois la génération. Bialetti Moka Express, Venus, Induction et Brikka.',
  canonical:'/accessoires/joint-cafetiere-italienne/',
  body:wrap('Joint de cafetière italienne : comment choisir la bonne taille ?','Le bon joint se choisit d’abord par modèle et taille. Chez Bialetti, plusieurs familles utilisent des packs différents et certaines générations ne sont pas interchangeables.','Accessoire · Joint',`
<section class="guide-answer"><span class="eyebrow">Avant de commander</span><h2>Ne cherchez pas un “joint moka universel”</h2><p>Bialetti vend des <strong>Ring & Filter Packs</strong> distincts : un groupe couvre notamment Moka Express, Moka Induction, Dama et Mini Express ; un autre est destiné aux Venus, Musa et Kitty. La taille de la cafetière doit ensuite correspondre à la référence du pack.</p><p>Pour Brikka et certaines Moka Induction, la génération peut aussi compter. Le catalogue actuel distingue par exemple des entonnoirs Moka Induction pré-2020 et des Brikka 2016–2023 ou 2024.</p></section>
<section><h2>La méthode la plus fiable pour identifier le joint</h2><ol class="decision-list"><li>Relevez le <strong>modèle exact</strong> de votre moka.</li><li>Identifiez sa <strong>taille en tasses</strong> ; ne la déduisez pas uniquement du diamètre extérieur de la cafetière.</li><li>Si le modèle ou la génération est incertain, mesurez l’ancien joint et la plaque filtrante puis comparez-les au tableau du fabricant.</li><li>Commandez le pack correspondant au couple modèle + taille, et à la génération lorsqu’elle est mentionnée.</li></ol></section>
<section><h2>Joint et filtre sont souvent vendus ensemble</h2><p>Sur plusieurs familles Bialetti, le pack contient <strong>un joint et une plaque filtrante</strong>. C’est utile parce que ces deux pièces travaillent au même niveau de la jonction entre chaudière et collecteur, mais cela ne signifie pas que l’entonnoir à café est inclus : l’entonnoir est une autre pièce.</p><p><a class="text-link" href="/accessoires/filtre-cafetiere-italienne/">Comprendre les filtres et entonnoirs</a></p></section>
<section><h2>Vous voulez remplacer le joint vous-même ?</h2><p>Cette page sert à choisir la pièce. Pour le démontage, le nettoyage de la portée et la remise en place, utilisez le <a class="text-link" href="/guides/changer-joint-cafetiere-italienne/">guide pour changer le joint d’une cafetière italienne</a>.</p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/moka-express-dama-mini-express-break-ring-filter-pack">Bialetti — Ring & Filter Pack aluminium / Moka Induction</a></li><li><a href="https://www.bialetti.co.nz/collections/spare-parts">Bialetti — catalogue pièces détachées</a></li></ul></section>`,`<h3>Règle n°1</h3><p>Modèle + taille + éventuellement génération. Une mesure de l’ancien joint permet de lever un doute.</p><span class="pill">Compatibilité</span><span class="pill">Joint + filtre</span>`)
 },
 'filtre-cafetiere-italienne':{
  title:'Filtre de cafetière italienne : plaque ou entonnoir, quelle pièce remplacer ?',
  description:'Filtre moka : distinguez la plaque filtrante supérieure de l’entonnoir à café et choisissez une pièce compatible avec votre cafetière.',
  canonical:'/accessoires/filtre-cafetiere-italienne/',
  body:wrap('Filtre de cafetière italienne : plaque ou entonnoir, quelle pièce remplacer ?','Le mot “filtre” désigne souvent deux pièces différentes sur une moka. Les identifier avant achat évite la majorité des erreurs de compatibilité.','Accessoire · Filtre',`
<section class="guide-answer"><span class="eyebrow">Deux pièces à ne pas confondre</span><h2>La plaque filtrante est en haut ; l’entonnoir contient le café moulu</h2><p>Chez Bialetti, la <strong>plaque filtrante</strong> est généralement vendue avec le joint dans un Ring & Filter Pack. L’<strong>entonnoir</strong>, qui se place dans la chaudière et reçoit le café moulu, est vendu séparément. Commander “un filtre” sans préciser laquelle de ces deux pièces vous cherchez mène facilement à la mauvaise référence.</p></section>
<section><h2>Si vous cherchez la plaque filtrante</h2><p>Identifiez le modèle et la taille, puis comparez le diamètre du filtre et du joint à la table Bialetti si vous avez un doute. Les packs Moka Express/Moka Induction et les packs Venus/Musa/Kitty ne sont pas les mêmes familles de pièces.</p><p><a class="text-link" href="/accessoires/joint-cafetiere-italienne/">Choisir le joint et le pack filtre</a></p></section>
<section><h2>Si vous cherchez l’entonnoir</h2><p>Bialetti publie des dimensions par taille pour les entonnoirs Moka Express : diamètre et longueur diffèrent notamment entre 2, 4, 6, 9 et 12 tasses. Le fabricant conseille de mesurer l’entonnoir existant lorsque la taille du pot est incertaine.</p><div class="guide-callout"><strong>Attention à la génération :</strong> le catalogue de pièces distingue aussi Moka Induction pré-2020 et actuelle, ainsi que plusieurs générations de Brikka. Une pièce visuellement proche n’est donc pas forcément interchangeable.</div></section>
<section><h2>Un filtre bouché n’est pas toujours un filtre à remplacer</h2><p>Bialetti déconseille les extraits, infusions et café instantané dans la moka parce qu’ils peuvent bloquer la plaque filtrante. Avant de commander une nouvelle pièce, vérifiez donc qu’il ne s’agit pas simplement d’un problème de nettoyage ou de mouture.</p><p><a class="text-link" href="/guides/nettoyer-cafetiere-italienne/">Nettoyer la cafetière</a> · <a class="text-link" href="/guides/mouture-cafetiere-italienne/">Choisir la mouture</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/moka-express-dama-mini-express-break-ring-filter-pack">Bialetti — plaques filtrantes et joints</a></li><li><a href="https://www.bialetti.co.nz/products/moka-express-dama-mini-express-break-funnels">Bialetti — entonnoirs et dimensions</a></li><li><a href="https://www.bialetti.co.nz/blogs/making-great-coffee/tips-and-care">Bialetti — conseils d’entretien</a></li></ul></section>`,`<h3>À identifier</h3><p>Plaque filtrante supérieure ou entonnoir à café ? Ce ne sont pas la même pièce.</p><span class="pill">Plaque filtrante</span><span class="pill">Entonnoir</span>`)
 },
 'pieces-detachees-bialetti':{
  title:'Pièces détachées Bialetti : trouver la bonne référence',
  description:'Pièces détachées Bialetti : joint, filtre, entonnoir et autres pièces par modèle, taille et génération de cafetière moka.',
  canonical:'/accessoires/pieces-detachees-bialetti/',
  body:wrap('Pièces détachées Bialetti : trouver la bonne référence','Bialetti maintient un catalogue de pièces pour plusieurs familles de moka, mais la compatibilité dépend du modèle, de la taille et parfois de la génération.','Accessoires · Bialetti',`
<section class="guide-answer"><span class="eyebrow">La bonne démarche</span><h2>Identifiez la cafetière avant la pièce</h2><p>Le catalogue Bialetti comprend actuellement des packs joint + filtre, des entonnoirs, certaines pièces 18 tasses et des références séparées pour plusieurs générations de Brikka et de Moka Induction. La bonne pièce n’est donc pas simplement “un joint Bialetti” ou “un filtre Bialetti”.</p></section>
<section><h2>Les pièces les plus courantes</h2><div class="table-wrap"><table class="guide-table"><thead><tr><th>Pièce</th><th>À quoi elle sert</th><th>Ce qu’il faut vérifier</th></tr></thead><tbody><tr><td>Joint</td><td>assurer l’étanchéité entre les deux parties</td><td>modèle + taille</td></tr><tr><td>Plaque filtrante</td><td>retenir le café sous le collecteur</td><td>souvent vendue avec le joint</td></tr><tr><td>Entonnoir</td><td>contenir le café moulu dans la chaudière</td><td>diamètre, longueur, modèle, taille</td></tr><tr><td>Poignée / pommeau</td><td>manipulation</td><td>disponibilité et procédure de montage selon marché</td></tr></tbody></table></div></section>
<section><h2>Les générations comptent</h2><p>Le catalogue actuel sépare explicitement les entonnoirs <strong>Moka Induction pré-2020</strong> des versions bi-layer plus récentes. Il distingue aussi une Brikka 2016–2023 de la Brikka actuelle 2024 pour certaines pièces. Si votre cafetière a plusieurs années, l’année ou la forme de la pièce peut donc être aussi importante que le nombre de tasses.</p></section>
<section><h2>Réparer avant de remplacer la cafetière</h2><p>Joint, plaque filtrante et entonnoir sont des pièces d’usure ou de service relativement simples à identifier. Bialetti indique d’ailleurs que les pièces soumises à l’usure normale ne sont pas couvertes comme défaut de fabrication par sa garantie de deux ans. Cela ne veut pas dire qu’il faut tout remplacer préventivement : changez une pièce parce qu’elle est usée, déformée, endommagée ou parce qu’un diagnostic l’impose.</p><p><a class="text-link" href="/guides/cafetiere-italienne-fuite-vapeur/">Diagnostiquer une fuite de vapeur</a> · <a class="text-link" href="/guides/changer-joint-cafetiere-italienne/">Changer un joint</a></p></section>
<section><h2>Pages dédiées</h2><p><a class="text-link" href="/accessoires/joint-cafetiere-italienne/">Choisir un joint</a> · <a class="text-link" href="/accessoires/filtre-cafetiere-italienne/">Choisir filtre ou entonnoir</a> · <a class="text-link" href="/marques/bialetti/">Comprendre la gamme Bialetti</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/collections/spare-parts">Bialetti — catalogue pièces détachées</a></li><li><a href="https://www.bialetti.co.nz/products/moka-express">Bialetti — disponibilité pièces et poignées</a></li><li><a href="https://www.bialetti.co.nz/blogs/making-great-coffee/tips-and-care">Bialetti — entretien, pièces et garantie</a></li></ul></section>`,`<h3>Ordre de vérification</h3><p>1. Modèle. 2. Taille. 3. Génération si nécessaire. 4. Dimensions de l’ancienne pièce.</p><span class="pill">Réparation</span><span class="pill">Compatibilité</span>`)
 }
};