const wrap=(title,intro,badge,body,aside)=>`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · <a href="/marques/">Marques</a> · ${title}</div><span class="eyebrow">${badge}</span><h1>${title}</h1><p>${intro}</p></div></section><div class="container template-grid brand-layout"><article class="content-main">${body}</article><aside><div class="sidebar-card"><span class="eyebrow">Repères</span>${aside}</div></aside></div>`;

export const brandHub={
 title:'Marques de cafetières italiennes',
 description:'Bialetti, Alessi ou Giannini : trois approches différentes de la moka, de la gamme pratique au design et à l’ingénierie inox.',
 canonical:'/marques/',
 body:`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · Marques</div><span class="eyebrow">Trois univers</span><h1>Marques de cafetières italiennes</h1><p>Bialetti, Alessi et Giannini répondent à trois logiques différentes : gamme et usage chez Bialetti, design et conception chez Alessi, architecture inox et fermeture chez Giannini.</p></div></section><section class="section"><div class="container brand-directory">
 <a class="brand-choice brand-choice--bialetti" href="/marques/bialetti/"><span class="eyebrow">Pratique & historique</span><h2>Bialetti</h2><p>Moka Express, Venus, Moka Induction, Brikka : partez de votre plaque et de la quantité préparée.</p><span class="brand-choice__path">Plaque → usage → volume</span><span class="card-link">Comprendre la gamme →</span></a>
 <a class="brand-choice brand-choice--alessi" href="/marques/alessi/"><span class="eyebrow">Design & collection</span><h2>Alessi</h2><p>9090, Pulcina, Vite, La Cupola : comparez des objets signés dont les choix de conception changent réellement.</p><span class="brand-choice__path">Designer → matériau → induction</span><span class="card-link">Explorer Alessi →</span></a>
 <a class="brand-choice brand-choice--giannini" href="/marques/giannini/"><span class="eyebrow">Inox & mécanique</span><h2>Giannini</h2><p>Giannina ou Tua : comparez fermeture, taille réductible et compatibilité induction réelle.</p><span class="brand-choice__path">Fermeture → taille → induction</span><span class="card-link">Explorer Giannini →</span></a>
 </div></section>`
};

export const brandPages={
 bialetti:{
  title:'Bialetti : quelle cafetière italienne choisir ?',
  description:'Bialetti en 2026 : Moka Express, Venus, Moka Induction, Brikka, Mini Express et variantes Exclusive. Comprendre plaque, taille, construction et pièces avant de choisir.',
  canonical:'/marques/bialetti/',
  body:wrap('Bialetti : quelle cafetière italienne choisir ?','La Moka Express reste l’icône de la marque, mais le catalogue Bialetti ne se résume plus à une seule forme. Pour choisir sans parcourir chaque couleur et chaque édition, partez de quatre décisions : votre plaque, le type de préparation, la façon dont vous voulez servir le café et le volume réellement préparé.','Marque · Bialetti',`
<section class="guide-answer"><span class="eyebrow">Réponse courte</span><h2>Commencez par quatre questions, pas par le nom du modèle</h2><ol class="decision-list"><li><strong>Votre plaque est-elle à induction ?</strong> Une Moka Express ou une Brikka classique en aluminium ne fonctionne pas directement sur induction ; plusieurs variantes Bialetti sont conçues pour cette plaque.</li><li><strong>Voulez-vous une moka classique ou le système Brikka ?</strong> La Brikka ajoute une valve spécifique et existe en version classique comme en version induction.</li><li><strong>Voulez-vous servir depuis une chambre haute ou directement dans deux tasses ?</strong> La Mini Express change réellement le geste de service : le café sort dans les deux tasses placées sous ses becs.</li><li><strong>Quel volume préparez-vous presque toujours ?</strong> Le nombre de « tasses » Bialetti est un nom de taille ; comparez ensuite le volume documenté de la variante exacte.</li></ol><p>Une fois ces quatre points fixés, les couleurs, finitions et éditions spéciales deviennent beaucoup plus faciles à trier.</p></section>
<section><h2>La gamme Bialetti est large, mais ses logiques sont plus simples que son catalogue</h2><div class="table-wrap"><table class="guide-table"><thead><tr><th>Logique</th><th>Références à regarder</th><th>Ce qui change réellement</th></tr></thead><tbody><tr><td>Moka classique en aluminium</td><td>Moka Express, Moka Exclusive classique et plusieurs éditions dérivées</td><td>forme et finition peuvent varier, mais pas d’induction directe sur les variantes aluminium documentées</td></tr><tr><td>Induction directe</td><td>Venus, Moka Induction, Moka Exclusive Induction, Brikka Induction, Mini Express Induction</td><td>construction de la base ou du corps adaptée à l’induction ; la taille exacte reste à vérifier</td></tr><tr><td>Préparation Brikka</td><td>Brikka classique, Brikka Induction</td><td>valve spécifique et méthode propre à cette famille</td></tr><tr><td>Service direct</td><td>Mini Express, Mini Express Induction</td><td>le café est dirigé directement vers deux tasses au lieu de remplir une chambre supérieure classique</td></tr></tbody></table></div><p>Cette lecture évite deux erreurs opposées : croire que chaque couleur correspond à une nouvelle cafetière, ou au contraire ramener toute la marque à Moka Express, Venus, Moka Induction et Brikka alors que certaines variantes changent réellement l’usage.</p></section>
<section><h2>Sur induction, Bialetti propose plusieurs réponses — elles ne sont pas équivalentes</h2><p>Le premier réflexe n’est pas de chercher le mot « inox », mais la <strong>variante exacte</strong>. Les fiches officielles consultées distinguent plusieurs constructions.</p><div class="comparison-picks"><div class="pick"><h3>Venus</h3><p>La voie inox 18/10. Sur la fiche actuelle consultée, les tailles 4 et 6 tasses sont compatibles induction tandis que la 2 tasses est explicitement exclue.</p><a class="text-link" href="/modeles/bialetti-venus/">Voir la fiche Venus →</a></div><div class="pick"><h3>Moka Induction</h3><p>Une chaudière bi-layer acier inoxydable + aluminium avec une partie supérieure en aluminium. Elle conserve davantage le langage de la Moka Express.</p><a class="text-link" href="/modeles/bialetti-moka-induction/">Voir la fiche Moka Induction →</a></div><div class="pick"><h3>Moka Exclusive Induction</h3><p>La silhouette Exclusive existe aussi avec une chaudière bi-layer conçue pour l’induction. L’Exclusive classique en aluminium, elle, n’est pas induction directe.</p></div></div><p>Bialetti commercialise aussi des Brikka Induction et Mini Express Induction. Cela montre pourquoi « Bialetti induction » n’est pas une famille unique : le choix reste lié à la construction et à l’usage souhaité.</p><div class="guide-callout"><strong>Deuxième hard gate :</strong> même lorsqu’une variante est annoncée induction, Bialetti demande de vérifier que le diamètre de sa base est détecté par votre table de cuisson. La compatibilité du matériau ne suffit donc pas à elle seule.</div><p><a class="text-link" href="/guides/cafetiere-italienne-induction-compatibilite/">Vérifier la compatibilité induction pas à pas →</a> · <a class="text-link" href="/comparatifs/cafetiere-italienne-induction/">Comparer les moka induction →</a></p></section>
<section><h2>Brikka : une branche de préparation, pas une Moka Express « plus haut de gamme »</h2><p>La Brikka mérite d’être séparée parce que Bialetti lui attribue une valve spécifique et une préparation distincte. C’est une différence de fonctionnement, pas une preuve automatique qu’elle produit un « meilleur » café.</p><p>La distinction de plaque compte ici aussi : la <strong>Brikka classique</strong> documentée est en aluminium et ne fonctionne pas directement sur induction, tandis qu’une <strong>Brikka Induction</strong> à base bi-layer existe. Acheter « une Brikka » sans vérifier la variante peut donc conduire à la même erreur que pour une Venus achetée uniquement sur son nom.</p><div class="guide-callout"><strong>Ce que la documentation permet de conclure :</strong> la valve spécifique distingue clairement Brikka de Moka Express. Elle ne suffit pas, à elle seule, à conclure à un meilleur goût, une utilisation plus facile ou une crema supérieure dans tous les usages.</div></section>
<section><h2>Mini Express : la différence est visible au moment de servir</h2><p>La Mini Express n’est pas seulement une petite Moka Express. Bialetti la conçoit pour envoyer le café directement dans <strong>deux tasses placées sous les becs</strong>. La version classique est en aluminium et n’est pas prévue pour l’induction directe ; la Mini Express Induction utilise une base bi-layer compatible induction.</p><p>Cette famille est donc pertinente si le service direct fait partie de ce que vous recherchez. Si vous voulez simplement une petite quantité dans une moka traditionnelle, commencez plutôt par la capacité et les modèles classiques.</p><p><a class="text-link" href="/capacites/">Partir du volume réellement préparé →</a></p></section>
<section><h2>Moka Exclusive, couleurs et collaborations : distinguez le design de la fonction</h2><p>Bialetti décline largement son langage visuel. Le catalogue consulté propose des Moka Express Black ou Italia et des gammes Exclusive, auxquelles s’ajoutent régulièrement des éditions ou collaborations. Le nom graphique ne suffit pas à dire si la mécanique change.</p><p>La <strong>Moka Exclusive classique</strong> consultée reste une cafetière en aluminium sans induction directe. La <strong>Moka Exclusive Induction</strong>, en revanche, change réellement sa construction avec une chaudière bi-layer et devient compatible induction. La différence pertinente est donc fonctionnelle : une finition ou un coloris ne doit pas être confondu avec une variante qui modifie la plaque ou l’usage.</p><div class="guide-callout"><strong>Réflexe utile :</strong> ne déduisez jamais la compatibilité d’une couleur, d’un nom de collection ou d’une collaboration. Vérifiez la fiche de la variante exacte.</div></section>
<section><h2>La taille peut renverser un choix qui semblait déjà fait</h2><p>Bialetti utilise des « tasses » de type espresso comme repère de taille, mais les volumes documentés varient selon les familles. Sur les fiches actuelles consultées, une Venus 4 tasses est donnée autour de 170 ml alors qu’une Moka Induction 4 tasses est donnée autour de 150 ml. Le même chiffre ne constitue donc pas une mesure universelle.</p><p>La marque recommande également de choisir une taille correspondant au service habituel plutôt que de sous-remplir systématiquement une grande moka. Avant de choisir la finition ou l’édition, vérifiez donc le volume de la variante exacte.</p><p><a class="text-link" href="/capacites/">Comparer les tailles et volumes documentés →</a> · <a class="text-link" href="/guides/dosage-cafe-cafetiere-italienne/">Comprendre le remplissage d’une moka →</a></p></section>
<section><h2>Les pièces détachées sont un vrai avantage d’écosystème — à condition d’identifier la génération</h2><p>Bialetti référence encore des jeux joint + filtre et des entonnoirs pour plusieurs familles. Le catalogue de pièces consulté montre toutefois pourquoi « c’est une Bialetti 4 tasses » n’est pas toujours une identification suffisante.</p><p>Les entonnoirs <strong>Moka Induction</strong> sont par exemple séparés entre version bi-layer actuelle et modèle pré-2020. Pour <strong>Brikka</strong>, Bialetti distingue des pièces pour les modèles 2016–2023 et le modèle courant 2024. La compatibilité doit donc se vérifier avec la famille, la taille et, lorsque le catalogue le demande, la génération.</p><p>Cette traçabilité est plus utile à long terme qu’une promesse vague de durabilité : elle vous dit ce qu’il faudra réellement identifier le jour où un joint, un filtre ou un entonnoir doit être remplacé.</p><p><a class="text-link" href="/accessoires/pieces-detachees-bialetti/">Voir le guide des pièces détachées Bialetti →</a></p></section>
<section><h2>Quelle page regarder après avoir choisi votre logique Bialetti ?</h2><div class="comparison-picks"><div class="pick"><h3>Moka classique hors induction</h3><p>La fiche Moka Express détaille construction, tailles, plaques et limites sans refaire toute la gamme.</p><a class="text-link" href="/modeles/bialetti-moka-express/">Voir Moka Express →</a></div><div class="pick"><h3>Inox et induction</h3><p>La fiche Venus permet de vérifier précisément la taille et l’exception 2 tasses.</p><a class="text-link" href="/modeles/bialetti-venus/">Voir Venus →</a></div><div class="pick"><h3>Silhouette moka sur induction</h3><p>La fiche Moka Induction explique sa construction bi-layer et ses volumes documentés.</p><a class="text-link" href="/modeles/bialetti-moka-induction/">Voir Moka Induction →</a></div><div class="pick"><h3>Vous hésitez encore avec une autre marque ?</h3><p>Quittez la logique Bialetti et revenez aux critères plaque, capacité, matériau et usage.</p><a class="text-link" href="/comparatifs/meilleure-cafetiere-italienne/">Comparer les cafetières italiennes →</a></div></div></section>
<section class="guide-sources" id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/collections/stovetop-espresso">Bialetti — collection stovetop actuelle consultée</a></li><li><a href="https://www.bialetti.co.nz/products/moka-express">Bialetti — Moka Express</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-venus-induction-copper">Bialetti — Venus : inox, tailles et induction</a></li><li><a href="https://www.bialetti.co.nz/products/copy-of-bialetti-moka-induction-red">Bialetti — Moka Induction Bi-Layer</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-brikka-new">Bialetti — Brikka classique</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-brikka-induction">Bialetti — Brikka Induction</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-mini-express-red-2-cup-set">Bialetti — Mini Express</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-mini-express-induction-2-cup-set">Bialetti — Mini Express Induction</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-moka-exclusive-red">Bialetti — Moka Exclusive classique</a></li><li><a href="https://www.bialetti.co.nz/collections/stainless-stovetop/products/bialetti-moka-exclusive-induction-grey">Bialetti — Moka Exclusive Induction</a></li><li><a href="https://www.bialetti.co.nz/collections/spare-parts">Bialetti — pièces détachées et différences de génération</a></li><li><a href="https://www.bialetti.co.nz/pages/history-heritage">Bialetti — histoire et lancement de la Moka Express en 1933</a></li></ul><p class="source-date">Sources vérifiées le 15 septembre 2026. La disponibilité commerciale exacte peut varier selon le pays et le moment.</p></section>`,`<h3>Quatre questions</h3><ol><li>Induction ou non ?</li><li>Moka classique ou Brikka ?</li><li>Chambre haute ou service direct ?</li><li>Quel volume réel ?</li></ol><p>Ensuite seulement : finition, couleur et édition.</p>`)
 },
 giannini:{
  title:"Giannini : faut-il choisir une Giannina ou une Tua ?",
  description:'Giannini en 2026 : Giannina Tradizione, Restyling et Tua. Comprendre fermeture, filtre réducteur, tailles et compatibilité induction avant de choisir.',
  canonical:'/marques/giannini/',
  body:wrap("Giannini : faut-il choisir une Giannina ou une Tua ?","Chez Giannini, le choix ne se résume pas à une finition inox. La vraie différence se joue dans l’architecture de la cafetière : fermeture non vissée de la Giannina ou fermeture classique à vis de la Tua, taille réellement utilisée et compatibilité induction de la version choisie.","Marque · Giannini",`
<section class="guide-answer"><span class="eyebrow">Réponse courte</span><h2>Commencez par quatre décisions</h2><ol class="decision-list"><li><strong>Voulez-vous la fermeture Giannina ?</strong> La Giannina se distingue par un système de fermeture non vissé ; la Tua revient à une fermeture à vis plus conventionnelle.</li><li><strong>Quelle quantité préparez-vous vraiment ?</strong> Les formats Giannina 3/1 et 6/3 sont documentés avec un filtre réducteur permettant deux quantités de préparation.</li><li><strong>Votre plaque est-elle à induction ?</strong> Les tailles 3/1 et 6/3 de la Giannina Restyling sont documentées comme compatibles induction, mais le format 1 tasse consulté ne l’est pas.</li><li><strong>Votre foyer détecte-t-il un petit diamètre ?</strong> Même avec une cafetière annoncée compatible induction, la détection du fond reste une contrainte réelle.</li></ol><p>Ce cadre est plus utile que de choisir d’abord entre Tradizione, Restyling ou Tua sur leur apparence.</p></section>
<section><h2>Giannina et Tua ne répondent pas à la même logique</h2><div class="table-wrap"><table class="guide-table"><thead><tr><th>Famille</th><th>Architecture</th><th>Quand la regarder</th></tr></thead><tbody><tr><td>Giannina Tradizione / Restyling</td><td>acier inoxydable, fermeture non vissée, logique de tailles réductibles sur plusieurs formats</td><td>si le système de fermeture et la construction Giannina font partie du choix</td></tr><tr><td>Tua</td><td>acier inoxydable poli, fermeture à vis, manche et pommeau résistants à la chaleur</td><td>si vous cherchez une moka inox Giannini plus conventionnelle dans son assemblage</td></tr></tbody></table></div><p>Il serait donc trompeur de présenter Tua comme une simple Giannina moins chère ou Giannina comme une Tua plus haut de gamme. La différence utile est d’abord mécanique.</p></section>
<section><h2>Giannina Tradizione ou Restyling : ce qui change réellement</h2><p>La Giannina historique est associée à Carlo Giannini et à 1968. Le Restyling, associé à Khodi Feiz, conserve le principe de fermeture non vissée mais retravaille notamment le manche et le couvercle.</p><p>Les sources actuelles consultées présentent le Restyling comme une évolution fonctionnelle et esthétique : manche redessiné, couvercle reposant à l’intérieur du corps pour améliorer le bec verseur, et adaptation de certaines tailles à l’induction.</p><div class="guide-callout"><strong>À retenir :</strong> Restyling n’est pas seulement un changement de couleur. En revanche, cela ne signifie pas que toutes les tailles partagent exactement les mêmes compatibilités.</div></section>
<section><h2>Induction : l’inox ne suffit pas à répondre oui</h2><p>La compatibilité induction dépend ici de la <strong>taille exacte</strong>. Les fiches consultées documentent les Giannina Restyling 3/1 et 6/3 pour l’induction, tandis que la version 1 tasse actuelle consultée est explicitement indiquée comme non compatible.</p><p>Il faut ensuite vérifier le seuil de détection de la plaque. La fiche 3/1 consultée signale un fond d’environ 7,7 cm pouvant poser problème sur certains foyers. Pour Tua, le distributeur consulté précise également qu’un foyer doit accepter un diamètre minimal d’environ 80 mm.</p><div class="guide-callout"><strong>Deuxième hard gate :</strong> une construction annoncée compatible induction ne garantit pas que votre foyer détectera un petit diamètre.</div><p><a class="text-link" href="/guides/cafetiere-italienne-induction-compatibilite/">Vérifier la compatibilité induction pas à pas →</a> · <a class="text-link" href="/comparatifs/cafetiere-italienne-induction/">Comparer les moka induction →</a></p></section>
<section><h2>Le filtre réducteur change la manière de choisir la taille</h2><p>Sur les Giannina 3/1 et 6/3 documentées, le filtre réducteur permet de préparer deux quantités différentes avec la même cafetière. Cela rend le chiffre de taille plus utile qu’un simple nom de format : une 6/3 peut couvrir deux usages prévus par la conception.</p><p>Cette souplesse ne doit toutefois pas être généralisée à toutes les Giannina. La fiche 1 tasse consultée indique justement l’absence de filtre réducteur.</p><p><a class="text-link" href="/capacites/">Comparer les tailles et volumes d’une moka →</a></p></section>
<section><h2>Tua : une alternative Giannini plus classique dans sa fermeture</h2><p>La Tua actuelle consultée reste une cafetière en acier inoxydable poli, mais elle abandonne la fermeture non vissée de la Giannina au profit d’une fermeture à vis. Les versions 3/1 et 6/3 relevées sont annoncées compatibles induction.</p><p>Elle mérite donc une place propre dans le hub : pas parce qu’elle serait « meilleure » ou « moins premium », mais parce qu’elle répond à un utilisateur qui veut une moka Giannini inox sans faire de la fermeture Giannina un critère essentiel.</p><p><a class="text-link" href="/comparatifs/cafetiere-italienne-inox/">Comparer les cafetières italiennes en inox →</a></p></section>
<section><h2>Pièces et entretien : vérifier la référence plutôt que supposer l’universalité</h2><p>Le distributeur spécialisé consulté propose encore des filtres réducteurs, joints, filtres supérieurs et soupapes pour plusieurs Giannina. C’est un signal utile pour l’après-vente, mais pas une garantie de stock permanent ni de compatibilité universelle entre tailles.</p><p>Pour une pièce, partez toujours de la famille, de la taille et de la référence exacte de la cafetière avant de commander.</p></section>
<section><h2>Quelle page regarder ensuite ?</h2><div class="comparison-picks"><div class="pick"><h3>Votre contrainte principale est l’induction</h3><p>Vérifiez d’abord la taille et le diamètre détecté par le foyer avant de comparer les finitions.</p><a class="text-link" href="/guides/cafetiere-italienne-induction-compatibilite/">Voir le guide induction →</a></div><div class="pick"><h3>Vous hésitez sur la quantité</h3><p>Le filtre réducteur Giannina rend le choix de taille particulier, mais le volume habituel reste le point de départ.</p><a class="text-link" href="/capacites/">Comparer les capacités →</a></div><div class="pick"><h3>Vous cherchez surtout une moka inox</h3><p>Replacez Giannini face aux autres constructions inox plutôt que de rester dans une logique de marque.</p><a class="text-link" href="/comparatifs/cafetiere-italienne-inox/">Comparer les modèles inox →</a></div><div class="pick"><h3>Vous hésitez encore entre marques</h3><p>Revenez aux critères plaque, capacité, matériau et architecture de fermeture.</p><a class="text-link" href="/comparatifs/meilleure-cafetiere-italienne/">Comparer les cafetières italiennes →</a></div></div></section>
<section class="guide-sources" id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.coltelleriacollini.it/giannini">Collini — gamme Giannini et Giannina</a></li><li><a href="https://www.coltelleriacollini.it/giannini-caffettiera-giannina-3-tazze-induzione.html">Collini — Giannina 3/1 induction</a></li><li><a href="https://www.coltelleriacollini.it/caffettiere/marchecoltelli-giannini">Collini — Tua 3/1 et 6/3</a></li><li><a href="https://giannini-shop.de/Giannini/1-Tasse-Giannini-Restyling-Espressokocher-3001010-Giannina%3A%3A424.html">Giannini Shop — Giannina Restyling 1 tasse</a></li><li><a href="https://giannini-shop.de/Giannini/3-1-Tassen-Giannini-Restyling-Espressokocher-3003010-Giannina%3A%3A242.html">Giannini Shop — Giannina Restyling 3/1</a></li><li><a href="https://giannini-shop.de/Giannini/6-3-Tassen-Giannini-Restyling-Espressokocher-3006010-Giannina%3A%3A243.html">Giannini Shop — Giannina Restyling 6/3</a></li><li><a href="https://www.pratmarmilano.it/prodotti/12-attrezzatura-per-cucina/1954-giannini-caffettiera-giannini-restyling-da-1-tazza-3-1-6-3-9-6-tazze.htm">Pratmar Milano — Giannina Tradizione et Restyling</a></li></ul></section>
`,`
<p><strong>Giannina</strong><br>Fermeture non vissée</p><p><strong>3/1 et 6/3</strong><br>Formats documentés avec filtre réducteur</p><p><strong>Induction</strong><br>Vérifier la taille et le diamètre du foyer</p><p><strong>Tua</strong><br>Alternative inox à fermeture vissée</p>
`)
 },
 alessi:{
  title:'Alessi : quelle cafetière italienne choisir ?',
  description:'9090, Vite, Pulcina, Moka ou La Cupola : comprendre les cafetières Alessi par designer, matériau et compatibilité.',
  canonical:'/marques/alessi/',
  body:wrap('Alessi : quelle cafetière italienne choisir ?','Chez Alessi, la moka n’est pas une seule famille déclinée : chaque modèle porte un parti pris de designer, un matériau et parfois une version induction distincte.','Marque · Alessi',`
<section class="guide-answer"><span class="eyebrow">La différence Alessi</span><h2>Choisissez d’abord le type d’objet que vous voulez vivre au quotidien</h2><p>La <strong>9090</strong> de Richard Sapper est l’icône technique en inox ; <strong>Vite</strong> représente la proposition contemporaine actuelle ; <strong>Pulcina</strong> de Michele De Lucchi travaille une silhouette sculpturale ; la <strong>Moka</strong> de David Chipperfield réinterprète la forme familière ; <strong>La Cupola</strong> d’Aldo Rossi assume presque une petite architecture de table.</p><p>Le prix ou le nom du designer ne prouvent pas un meilleur café. Ce qui change concrètement, ce sont la construction, la fermeture, le matériau, la taille et la compatibilité avec votre plaque.</p></section>
<section><h2>Cinq modèles, cinq logiques</h2><div class="comparison-picks"><div class="pick"><span class="eyebrow">Fonction + icône</span><h3>9090 — Richard Sapper</h3><p>Inox 18/10, base élargie, bec anti-goutte et fermeture à levier. C’est la référence Alessi la plus directement liée à des innovations fonctionnelles documentées.</p></div><div class="pick"><span class="eyebrow">Contemporain</span><h3>Vite</h3><p>Une proposition récente de la collection, disponible en version induction. Elle vise moins le patrimoine historique que la présence graphique contemporaine.</p></div><div class="pick"><span class="eyebrow">Sculptural</span><h3>Pulcina — Michele De Lucchi</h3><p>Fonte d’aluminium et silhouette en gradins. Une variante induction distincte existe : vérifiez donc la référence exacte.</p></div><div class="pick"><span class="eyebrow">Architecture</span><h3>La Cupola — Aldo Rossi</h3><p>Le modèle original date de 1988. Une version induction dédiée, avec fond en acier magnétique, a été introduite en 2025.</p></div></div></section>
<section><h2>9090 n’est pas seulement “la plus premium”</h2><p>La 9090 mérite une place à part parce que son dessin répond aussi à des problèmes d’usage : Alessi documente une base élargie, un bec anti-goutte et une fermeture à levier. L’inox 18/10 et la construction magnétique des références compatibles induction la distinguent des modèles Alessi en fonte d’aluminium.</p><p><a class="text-link" href="/modeles/alessi-9090/">Voir la page Alessi 9090</a> · <a class="text-link" href="/comparatifs/cafetiere-italienne-inox/">Comparer les moka inox</a></p></section>
<section><h2>Induction : le nom du modèle ne suffit pas toujours</h2><p>Pulcina et La Cupola illustrent bien le piège : Alessi vend ou a lancé des variantes spécifiques avec fond induction, distinctes des versions classiques. La Cupola classique reste une cafetière en fonte d’aluminium, tandis que la version induction 6 tasses lancée en 2025 ajoute un fond en acier magnétique.</p><p>Si votre priorité est la plaque plutôt que le design, passez directement au <a class="text-link" href="/comparatifs/cafetiere-italienne-induction/">comparatif induction</a>. Si l’objet compte autant que la fonction, le <a class="text-link" href="/comparatifs/cafetiere-italienne-design/">comparatif design</a> distingue mieux les partis pris.</p></section>
<section><h2>Et la Moka de David Chipperfield ?</h2><p>Elle occupe un rôle différent : Alessi la présente comme une interprétation d’auteur d’une forme familière. Elle est pertinente si vous voulez entrer dans l’univers de la marque sans forcément chercher le mécanisme singulier de la 9090 ou l’expression plus sculpturale de Pulcina.</p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://alessi.com/fr/collections/coffee-makers">Alessi — collection cafetières</a></li><li><a href="https://alessi.com/products/9090-espresso-coffee-maker">Alessi — 9090</a></li><li><a href="https://alessi.com/fr/products/pulcina-espresso-coffee-maker-1">Alessi — Pulcina classique</a></li><li><a href="https://alessi.com/fr/products/pulcina-espresso-coffee-maker-induction">Alessi — Pulcina induction</a></li><li><a href="https://alessi.com/fr/products/la-cupola-espresso-coffee-maker">Alessi — La Cupola classique</a></li><li><a href="https://alessi.com/fr/products/la-cupola-espresso-coffee-maker-1">Alessi — La Cupola induction</a></li><li><a href="https://alessi.com/fr/products/moka-espresso-coffee-maker">Alessi — Moka de David Chipperfield</a></li></ul></section>`,`<h3>À retenir</h3><p>Chez Alessi, vérifiez la référence exacte : matériau et induction peuvent changer entre variantes d’un même nom.</p><span class="pill">9090</span><span class="pill">Pulcina</span><span class="pill">Design</span>`)
 }
};