const wrap=(title,intro,badge,body,aside)=>`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · <a href="/marques/">Marques</a> · ${title}</div><span class="eyebrow">${badge}</span><h1>${title}</h1><p>${intro}</p></div></section><div class="container template-grid brand-layout"><article class="content-main">${body}</article><aside><div class="sidebar-card"><span class="eyebrow">Repères</span>${aside}</div></aside></div>`;

export const brandHub={
 title:'Marques de cafetières italiennes',
 description:'Bialetti ou Alessi : deux approches très différentes de la moka, de la gamme pratique au design italien.',
 canonical:'/marques/',
 body:`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · Marques</div><span class="eyebrow">Deux univers</span><h1>Marques de cafetières italiennes</h1><p>Bialetti et Alessi ne répondent pas à la même logique d’achat : l’une structure surtout le choix par gamme, taille et plaque ; l’autre par design, matériau et niveau de finition.</p></div></section><section class="section"><div class="container brand-directory"><a class="brand-choice" href="/marques/bialetti/"><span class="eyebrow">Pratique & historique</span><h2>Bialetti</h2><p>Moka Express, Venus, Moka Induction, Brikka : partez de votre plaque et de la quantité préparée.</p><span class="card-link">Comprendre la gamme →</span></a><a class="brand-choice" href="/marques/alessi/"><span class="eyebrow">Design & collection</span><h2>Alessi</h2><p>9090, Pulcina, Vite, La Cupola : comparez des objets signés dont les choix de conception changent réellement.</p><span class="card-link">Explorer Alessi →</span></a></div></section>`
};

export const brandPages={
 bialetti:{
  title:'Bialetti : quelle cafetière italienne choisir ?',
  description:'Moka Express, Venus, Moka Induction ou Brikka : comprendre la gamme Bialetti selon la plaque, la taille et l’usage.',
  canonical:'/marques/bialetti/',
  body:wrap('Bialetti : quelle cafetière italienne choisir ?','La marque historique couvre plusieurs logiques de moka. La bonne porte d’entrée n’est pas le nom le plus connu, mais votre plaque, la taille utile et le type de préparation recherché.','Marque · Bialetti',`
<section class="guide-answer"><span class="eyebrow">Choisir sans se perdre</span><h2>Quatre familles suffisent pour comprendre l’essentiel</h2><p><strong>Moka Express</strong> si vous cherchez la moka classique et n’avez pas besoin d’induction directe. <strong>Venus</strong> si vous privilégiez l’inox et une compatibilité plus large. <strong>Moka Induction</strong> si vous voulez rester proche de la silhouette classique sur induction. <strong>Brikka</strong> si sa valve spécifique et son style de préparation sont précisément ce que vous recherchez.</p><p>Le reste de la décision se joue surtout sur la taille : chez Bialetti, les “tasses” désignent de petites portions de café, pas des mugs.</p></section>
<section><h2>La gamme Bialetti, par besoin réel</h2><div class="table-wrap"><table class="guide-table"><thead><tr><th>Famille</th><th>Logique</th><th>Induction</th><th>À retenir</th></tr></thead><tbody><tr><td>Moka Express</td><td>la référence classique en aluminium</td><td>Non, pas directement</td><td>gaz, électrique et vitrocéramique ; adaptateur possible</td></tr><tr><td>Venus</td><td>construction inox</td><td>Oui selon taille</td><td>la 2 tasses fait exception et n’est pas documentée comme induction</td></tr><tr><td>Moka Induction</td><td>architecture moka avec base adaptée</td><td>Oui</td><td>choix cohérent si l’esthétique classique compte</td></tr><tr><td>Brikka / Brikka Induction</td><td>valve spécifique et préparation distincte</td><td>selon version</td><td>ne pas confondre Brikka classique et Brikka Induction</td></tr></tbody></table></div></section>
<section><h2>Le vrai piège : choisir le nom avant la taille</h2><p>Une Bialetti 2 tasses n’est pas l’équivalent de deux grandes tasses. Le distributeur officiel Bialetti en Nouvelle-Zélande donne environ 30 ml par “tasse” sur ses repères généraux et rappelle qu’une moka doit être utilisée avec sa capacité prévue. Autrement dit, acheter plus grand “au cas où” n’est pas neutre.</p><p>Sur induction, le diamètre ajoute une seconde contrainte : la <strong>Venus 2 tasses</strong> est explicitement exclue de la compatibilité induction alors que les tailles supérieures de la gamme le sont. Le nom Venus seul ne suffit donc pas.</p><p><a class="text-link" href="/capacites/">Choisir une capacité</a> · <a class="text-link" href="/comparatifs/cafetiere-italienne-induction/">Comparer les modèles induction</a></p></section>
<section><h2>Un avantage concret de Bialetti : les pièces restent identifiables</h2><p>La marque distribue encore des jeux joint + filtre et des entonnoirs pour plusieurs familles. La liste distingue même certaines générations de Brikka et les Moka Induction pré-2020 des versions plus récentes. C’est plus utile à long terme qu’une promesse vague de “durabilité” : avant d’acheter une pièce, vérifiez le modèle, la taille et, lorsque c’est pertinent, la génération.</p><p><a class="text-link" href="/accessoires/pieces-detachees-bialetti/">Voir le guide des pièces détachées</a></p></section>
<section><h2>Quelle Bialetti regarder ensuite ?</h2><div class="comparison-picks"><div class="pick"><h3>Moka Express</h3><p>Le point de départ hors induction : architecture simple, nombreuses tailles et pièces faciles à identifier.</p><a class="text-link" href="/modeles/bialetti-moka-express/">Voir le modèle →</a></div><div class="pick"><h3>Venus</h3><p>Le choix inox à regarder en priorité si votre plaque et votre taille sont compatibles.</p><a class="text-link" href="/modeles/bialetti-venus/">Voir le modèle →</a></div><div class="pick"><h3>Moka Induction</h3><p>Pour rester dans l’univers moka classique tout en passant à l’induction.</p><a class="text-link" href="/modeles/bialetti-moka-induction/">Voir le modèle →</a></div><div class="pick"><h3>Vous hésitez encore ?</h3><p>Le comparatif général repart de la plaque, de la capacité et du matériau plutôt que de la marque.</p><a class="text-link" href="/comparatifs/meilleure-cafetiere-italienne/">Comparer les cafetières →</a></div></div></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/moka-express">Bialetti — Moka Express</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-venus-induction-copper">Bialetti — Venus</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-brikka-new">Bialetti — Brikka et repères de taille</a></li><li><a href="https://www.bialetti.co.nz/collections/stovetop-espresso">Bialetti — gamme stovetop</a></li><li><a href="https://www.bialetti.co.nz/collections/spare-parts">Bialetti — pièces détachées</a></li></ul></section>`,`<h3>À retenir</h3><p>Commencez par la plaque et la taille. Le nom de gamme vient ensuite.</p><span class="pill">Moka Express</span><span class="pill">Venus</span><span class="pill">Induction</span>`)
 },
 alessi:{
  title:'Alessi : quelle cafetière italienne choisir ?',
  description:'9090, Vite, Pulcina, Moka ou La Cupola : comprendre les cafetières Alessi par designer, matériau et compatibilité.',
  canonical:'/marques/alessi/',
  body:wrap('Alessi : quelle cafetière italienne choisir ?','Chez Alessi, la moka n’est pas une seule famille déclinée : chaque modèle porte un parti pris de designer, un matériau et parfois une version induction distincte.','Marque · Alessi',`
<section class="guide-answer"><span class="eyebrow">La différence Alessi</span><h2>Choisissez d’abord le type d’objet que vous voulez vivre au quotidien</h2><p>La <strong>9090</strong> de Richard Sapper est l’icône technique en inox ; <strong>Vite</strong> représente la proposition contemporaine actuelle ; <strong>Pulcina</strong> de Michele De Lucchi travaille une silhouette sculpturale ; la <strong>Moka</strong> de David Chipperfield réinterprète la forme familière ; <strong>La Cupola</strong> d’Aldo Rossi assume presque une petite architecture de table.</p><p>Le prix ou le nom du designer ne prouvent pas un meilleur café. Ce qui change concrètement, ce sont la construction, la fermeture, le matériau, la taille et la compatibilité avec votre plaque.</p></section>
<section><h2>Cinq modèles, cinq logiques</h2><div class="comparison-picks"><div class="pick"><span class="eyebrow">Fonction + icône</span><h3>9090 — Richard Sapper</h3><p>Inox 18/10, base élargie, bec anti-goutte et fermeture à levier. C’est la référence Alessi la plus directement liée à des innovations fonctionnelles documentées.</p></div><div class="pick"><span class="eyebrow">Contemporain</span><h3>Vite</h3><p>Une proposition récente de la collection, disponible en version induction. Elle vise moins le patrimoine historique que la présence graphique contemporaine.</p></div><div class="pick"><span class="eyebrow">Sculptural</span><h3>Pulcina — Michele De Lucchi</h3><p>Fonte d’aluminium et silhouette en gradins. Une variante induction distincte existe : vérifiez donc la référence exacte.</p></div><div class="pick"><span class="eyebrow">Architecture</span><h3>La Cupola — Aldo Rossi</h3><p>Le modèle original date de 1988. Une version induction dédiée, avec fond en acier magnétique, a été introduite en 2025.</p></div></div></section>
<section><h2>9090 n’est pas seulement “la plus premium”</h2><p>La 9090 mérite une place à part parce que son dessin répond aussi à des problèmes d’usage : Alessi documente une base élargie, un bec anti-goutte et une fermeture à levier. L’inox 18/10 et la construction magnétique des références compatibles induction la distinguent des modèles Alessi en fonte d’aluminium.</p><p><a class="text-link" href="/modeles/alessi-9090/">Voir la page Alessi 9090</a> · <a class="text-link" href="/comparatifs/cafetiere-italienne-inox/">Comparer les moka inox</a></p></section>
<section><h2>Induction : le nom du modèle ne suffit pas toujours</h2><p>Pulcina et La Cupola illustrent bien le piège : Alessi vend ou a lancé des variantes spécifiques avec fond induction, distinctes des versions classiques. La Cupola classique reste une cafetière en fonte d’aluminium, tandis que la version induction 6 tasses lancée en 2025 ajoute un fond en acier magnétique.</p><p>Si votre priorité est la plaque plutôt que le design, passez directement au <a class="text-link" href="/comparatifs/cafetiere-italienne-induction/">comparatif induction</a>. Si l’objet compte autant que la fonction, le <a class="text-link" href="/comparatifs/cafetiere-italienne-design/">comparatif design</a> distingue mieux les partis pris.</p></section>
<section><h2>Et la Moka de David Chipperfield ?</h2><p>Elle occupe un rôle différent : Alessi la présente comme une interprétation d’auteur d’une forme familière. Elle est pertinente si vous voulez entrer dans l’univers de la marque sans forcément chercher le mécanisme singulier de la 9090 ou l’expression plus sculpturale de Pulcina.</p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://alessi.com/fr/collections/coffee-makers">Alessi — collection cafetières</a></li><li><a href="https://alessi.com/products/9090-espresso-coffee-maker">Alessi — 9090</a></li><li><a href="https://alessi.com/fr/products/pulcina-espresso-coffee-maker-1">Alessi — Pulcina classique</a></li><li><a href="https://alessi.com/fr/products/pulcina-espresso-coffee-maker-induction">Alessi — Pulcina induction</a></li><li><a href="https://alessi.com/fr/products/la-cupola-espresso-coffee-maker">Alessi — La Cupola classique</a></li><li><a href="https://alessi.com/fr/products/la-cupola-espresso-coffee-maker-1">Alessi — La Cupola induction</a></li><li><a href="https://alessi.com/fr/products/moka-espresso-coffee-maker">Alessi — Moka de David Chipperfield</a></li></ul></section>`,`<h3>À retenir</h3><p>Chez Alessi, vérifiez la référence exacte : matériau et induction peuvent changer entre variantes d’un même nom.</p><span class="pill">9090</span><span class="pill">Pulcina</span><span class="pill">Design</span>`)
 }
};