import fs from 'node:fs';import path from 'node:path';
import { guidePages } from './guide-content.mjs';
import { guideHowToPages } from './guide-content-howto.mjs';
import { guideFirstUsePages } from './guide-content-first-use.mjs';
import { guideBrewBasicsPages } from './guide-content-brew-basics.mjs';
const root=path.resolve(import.meta.dirname,'..');
const pages={
  comparatifs:['meilleure-cafetiere-italienne','cafetiere-italienne-induction','cafetiere-italienne-inox','cafetiere-italienne-electrique','cafetiere-italienne-design','petite-cafetiere-italienne'],
  marques:['bialetti','alessi'],
  modeles:['bialetti-moka-express','bialetti-venus','bialetti-moka-induction','alessi-9090'],
  capacites:['cafetiere-italienne-2-tasses','cafetiere-italienne-4-tasses','cafetiere-italienne-6-tasses','cafetiere-italienne-10-tasses','cafetiere-italienne-12-tasses'],
  guides:['comment-choisir-cafetiere-italienne','comment-utiliser-cafetiere-italienne','premiere-utilisation-cafetiere-italienne','dosage-cafe-cafetiere-italienne','mouture-cafetiere-italienne','quel-cafe-pour-cafetiere-italienne','cafetiere-italienne-aluminium-ou-inox','cafetiere-italienne-induction-compatibilite','nettoyer-cafetiere-italienne','detartrer-cafetiere-italienne','cafetiere-italienne-cafe-amer-brule','cafetiere-italienne-fuite-vapeur','changer-joint-cafetiere-italienne','cafetiere-italienne-vs-espresso'],
  accessoires:['adaptateur-induction-cafetiere-italienne','joint-cafetiere-italienne','filtre-cafetiere-italienne','pieces-detachees-bialetti'],
  'cafe-moka':['quest-ce-que-le-cafe-moka','comment-preparer-un-cafe-moka']
};
const labels={comparatifs:'Comparatifs',marques:'Marques',modeles:'Modèles',capacites:'Par taille',guides:'Guides',accessoires:'Accessoires','cafe-moka':'Café moka'};
const title=s=>s.split('-').map((w,i)=>['inox','bialetti','alessi'].includes(w)?w[0].toUpperCase()+w.slice(1):i===0?w[0].toUpperCase()+w.slice(1):w).join(' ').replace('Quest ce','Qu’est-ce').replace('cafetiere','cafetière').replace('italienne','italienne').replace('electrique','électrique').replace('detartrer','détartrer').replace('premiere','première').replace('cafe','café').replace('moka express','Moka Express').replace('moka induction','Moka Induction');
const header=`<div class="top-note">Guide indépendant · Comparatifs transparents · Liens affiliés signalés</div><header class="site-header"><div class="container header-row"><a class="brand" href="/"><img src="/assets/logo.svg" alt=""><span>Cafetière Italienne</span></a><nav class="nav"><a href="/comparatifs/">Comparatifs</a><a href="/marques/bialetti/">Bialetti</a><a href="/capacites/">Par taille</a><a href="/guides/">Guides</a><a href="/guides/nettoyer-cafetiere-italienne/">Entretien</a></nav><button class="search-btn" aria-label="Rechercher">⌕</button><button class="menu-btn" aria-label="Menu">☰</button></div></header><div class="quick-nav"><div class="quick-row"><a href="/comparatifs/cafetiere-italienne-induction/">Induction</a><a href="/capacites/cafetiere-italienne-2-tasses/">2 tasses</a><a href="/capacites/cafetiere-italienne-4-tasses/">4 tasses</a><a href="/capacites/cafetiere-italienne-6-tasses/">6 tasses</a><a href="/comparatifs/cafetiere-italienne-inox/">Inox</a></div></div>`;
const footer=`<footer class="site-footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="/"><img src="/assets/logo.svg" alt="">Cafetière Italienne</a><p class="footer-about">Le guide spécialisé pour choisir, utiliser et entretenir sa cafetière moka.</p></div><div><h4>Choisir</h4><a href="/comparatifs/">Comparatifs</a><a href="/comparatifs/cafetiere-italienne-induction/">Induction</a><a href="/capacites/">Par taille</a><a href="/marques/bialetti/">Bialetti</a></div><div><h4>Apprendre</h4><a href="/guides/comment-utiliser-cafetiere-italienne/">Comment utiliser</a><a href="/guides/dosage-cafe-cafetiere-italienne/">Dosage</a><a href="/guides/mouture-cafetiere-italienne/">Mouture</a><a href="/guides/nettoyer-cafetiere-italienne/">Entretien</a></div><div><h4>Le site</h4><a href="/a-propos/">À propos</a><a href="/notre-methode/">Notre méthode</a><a href="/affiliation/">Affiliation</a><a href="/contact/">Contact</a></div></div><div class="footer-bottom">© 2026 Cafetière Italienne <span>Informations vérifiées auprès des fabricants</span></div></div></footer>`;
const siteBase=process.env.SITE_BASE||'/';
const shell=(t,body,desc='Guide spécialisé consacré aux cafetières italiennes.',opts={})=>{const robots=opts.robots||'index,follow';const canonical=opts.canonical?`<link rel="canonical" href="https://cafetiere-italienne.be${opts.canonical}">`:'';return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><base href='${siteBase}'><title>${t} | Cafetière Italienne</title><meta name="description" content="${desc}"><meta name="robots" content="${robots}">${canonical}<link rel="icon" href="assets/logo.svg"><link rel="stylesheet" href="assets/styles.css"></head><body>${header}<main>${body}</main>${footer}<script src="assets/app.js"></script></body></html>`.replaceAll('href="/','href="');};
const home=`<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">Le guide expert du café moka</span><h1>Trouvez la moka <em>faite pour vous.</em></h1><p>Comparez les modèles, les tailles et les matériaux pour préparer un vrai café moka à la maison.</p><div class="actions"><a class="btn btn-primary" href="/comparatifs/meilleure-cafetiere-italienne/">Comparer les cafetières →</a><a class="btn btn-secondary" href="/guides/comment-choisir-cafetiere-italienne/">Comment choisir</a></div></div><div class="hero-visual"><div class="sun"></div><div class="moka-illustration" aria-label="Illustration d’une cafetière moka"><div class="steam">∿</div><div class="moka-knob"></div><div class="moka-spout"></div><div class="moka-top"></div><div class="moka-band"></div><div class="moka-body"></div><div class="moka-handle"></div></div><div class="hero-badge"><strong>La bonne taille</strong>2, 4, 6 ou 10 tasses ?</div></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Choisir simplement</span><h2>Quelle cafetière recherchez-vous ?</h2></div><p>Trois portes d’entrée pour trouver rapidement un modèle adapté à votre cuisine et à vos habitudes.</p></div><div class="cards"><a class="need-card" href="/comparatifs/cafetiere-italienne-induction/"><span class="card-icon">⌁</span><h3>Pour l’induction</h3><p class="muted">Les modèles réellement compatibles avec votre plaque.</p><span class="card-link">Découvrir →</span></a><a class="need-card" href="/marques/bialetti/"><span class="card-icon">◇</span><h3>Une Bialetti</h3><p class="muted">Comprendre les gammes de la marque historique.</p><span class="card-link">Voir les modèles →</span></a><a class="need-card" href="/comparatifs/cafetiere-italienne-inox/"><span class="card-icon">◌</span><h3>En inox</h3><p class="muted">Robuste, moderne et facile à entretenir.</p><span class="card-link">Comparer →</span></a></div></div></section>
<section class="section sizes"><div class="container"><div class="section-head"><div><span class="eyebrow">Notre signature</span><h2>Combien de cafés préparez-vous ?</h2></div><p>Une “tasse” moka est plus petite qu’une tasse classique. Choisissez selon le volume réel.</p></div><div class="size-grid">${[['2','≈ 90 ml','1 personne'],['4','≈ 180 ml','1–2 personnes'],['6','≈ 270 ml','2–3 personnes'],['10','≈ 450 ml','4–5 personnes'],['12','≈ 540 ml','5–6 personnes']].map(([n,ml,p])=>`<a class="size-card" href="/capacites/cafetiere-italienne-${n}-tasses/"><div class="cups">${'<i class="cup"></i>'.repeat(Math.min(Number(n)/2,5))}</div><strong>${n} tasses</strong><span>${ml}</span><span>${p}</span></a>`).join('')}</div></div></section>
<section class="section" id="finder"><div class="container finder-wrap"><div class="finder-intro"><span class="eyebrow">Moka Finder</span><h2>Quelle moka est faite pour vous ?</h2><p>Répondez à trois questions. Nous vous orientons vers le bon type de cafetière.</p></div><div class="finder"><div class="finder-questions"><div class="finder-progress"><i class="on"></i><i></i><i></i></div><div class="finder-step active"><h3>Votre plaque ?</h3><div class="options"><button class="option" data-key="plaque" data-value="Gaz">Gaz</button><button class="option" data-key="plaque" data-value="Induction">Induction</button><button class="option" data-key="plaque" data-value="Vitrocéramique">Vitrocéramique</button><button class="option" data-key="plaque" data-value="Électrique">Électrique</button></div></div><div class="finder-step"><h3>Combien de personnes ?</h3><div class="options"><button class="option" data-key="taille" data-value="2 tasses">1</button><button class="option" data-key="taille" data-value="4 tasses">2</button><button class="option" data-key="taille" data-value="6 tasses">3–4</button><button class="option" data-key="taille" data-value="10 tasses">5+</button></div></div><div class="finder-step"><h3>Votre budget ?</h3><div class="options"><button class="option" data-key="budget" data-value="€">€ Essentiel</button><button class="option" data-key="budget" data-value="€€">€€ Confort</button><button class="option" data-key="budget" data-value="€€€">€€€ Design</button></div></div></div><div class="finder-result"><span class="eyebrow">Votre résultat</span><h3>Votre profil moka</h3><div class="result-card" data-result></div><a class="btn btn-primary" href="/comparatifs/meilleure-cafetiere-italienne/">Voir les modèles adaptés</a> <button class="reset">Recommencer</button></div></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Bien préparer</span><h2>Le moka, geste après geste</h2></div><a class="card-link" href="/guides/">Tous les guides →</a></div><div class="editorial-grid"><a class="feature-story" href="/guides/comment-utiliser-cafetiere-italienne/"><div class="feature-art">♨</div><div class="feature-copy"><span class="eyebrow">Guide essentiel</span><h3>Comment utiliser une cafetière italienne ?</h3><p class="muted">Les bons gestes, de l’eau jusqu’au service.</p></div></a><div class="story-list">${[['01','Trouver le bon dosage','/guides/dosage-cafe-cafetiere-italienne/'],['02','Choisir la mouture','/guides/mouture-cafetiere-italienne/'],['03','Éviter un café amer','/guides/cafetiere-italienne-cafe-amer-brule/'],['04','Nettoyer sa moka','/guides/nettoyer-cafetiere-italienne/']].map(([n,t,u])=>`<a class="story" href="${u}"><span class="story-num">${n}</span><strong>${t}</strong><span>→</span></a>`).join('')}</div></div></div></section>
<section class="section"><div class="container trust"><div><strong>Comparatifs indépendants</strong><span>Une sélection fondée sur l’usage, pas sur la remise affichée.</span></div><div><strong>Données structurées</strong><span>Matériau, volume réel, compatibilité et pièces détachées.</span></div><div><strong>Informations vérifiées</strong><span>Caractéristiques issues des fabricants et manuels officiels.</span></div></div></section>`;
fs.writeFileSync(path.join(root,'index.html'),shell('Cafetières italiennes : comparatifs, modèles et conseils',home,'Comparez les cafetières italiennes, les modèles, les tailles et les matériaux pour choisir la moka adaptée à votre cuisine.'));
for(const [cat,slugs] of Object.entries(pages)){
 const dir=path.join(root,cat);fs.mkdirSync(dir,{recursive:true});
 const links=slugs.map(s=>`<a href="/${cat}/${s}/">${title(s)} <span>→</span></a>`).join('');
 fs.writeFileSync(path.join(dir,'index.html'),shell(labels[cat],`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · ${labels[cat]}</div><span class="eyebrow">Explorer</span><h1>${labels[cat]}</h1><p>Retrouvez toutes les pages prévues pour cette rubrique. Les contenus éditoriaux seront ajoutés ultérieurement.</p></div></section><section class="section"><div class="container directory">${links}</div></section>`));
 for(const slug of slugs){const p=path.join(dir,slug);fs.mkdirSync(p,{recursive:true});const t=title(slug);const custom=cat==='guides'?(guidePages[slug]||guideHowToPages[slug]||guideFirstUsePages[slug]||guideBrewBasicsPages[slug]):null;if(custom){fs.writeFileSync(path.join(p,'index.html'),shell(custom.title,custom.body,custom.description,{robots:'noindex,follow',canonical:custom.canonical}));continue;}const tags=cat==='modeles'?'<span class="pill">Matériau</span><span class="pill">Capacité</span><span class="pill">Induction</span>':'<span class="pill">Guide expert</span><span class="pill">À compléter</span>';fs.writeFileSync(path.join(p,'index.html'),shell(t,`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · <a href="/${cat}/">${labels[cat]}</a> · ${t}</div><span class="eyebrow">${labels[cat]}</span><h1>${t}</h1><p>Gabarit prêt à recevoir le contenu éditorial et les données produit.</p></div></section><div class="container template-grid"><article><section class="placeholder"><h2>Introduction / réponse courte</h2><p class="muted">Zone de contenu à rédiger.</p></section><section class="placeholder"><h2>Bloc principal</h2><p class="muted">Comparatif, étapes, critères ou caractéristiques selon le type de page.</p></section><section class="placeholder"><h2>Questions fréquentes</h2><p class="muted">Réponses structurées pour le SEO et le GEO.</p></section></article><aside><div class="sidebar-card"><span class="eyebrow">Repères</span><h3>En un coup d’œil</h3><p>Composant contextuel prévu pour les informations décisives.</p>${tags}</div></aside></div>`));}
}
for(const [slug,t] of [['a-propos','À propos'],['notre-methode','Notre méthode'],['affiliation','Transparence & affiliation'],['contact','Contact']]){const d=path.join(root,slug);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'index.html'),shell(t,`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · ${t}</div><span class="eyebrow">Le site</span><h1>${t}</h1><p>Gabarit prêt à recevoir le contenu éditorial.</p></div></section><section class="section"><div class="container"><div class="placeholder"><h2>Contenu à rédiger</h2></div></div></section>`));}
console.log(`Site généré : ${1+Object.values(pages).flat().length+Object.keys(pages).length+4} pages.`);
