const wrap=(title,intro,badge,body,aside)=>`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · <a href="/capacites/">Par taille</a> · ${title}</div><span class="eyebrow">${badge}</span><h1>${title}</h1><p>${intro}</p></div></section><div class="container template-grid capacity-layout"><article class="content-main">${body}</article><aside><div class="sidebar-card"><span class="eyebrow">Repères</span>${aside}</div></aside></div>`;

export const capacityHub={
 title:'Quelle taille de cafetière italienne choisir ?',
 description:'2, 4, 6, 10 ou 12 tasses : choisissez une cafetière italienne selon le volume réellement préparé, pas selon un nombre de personnes.',
 canonical:'/capacites/',
 body:`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · Par taille</div><span class="eyebrow">Volume avant personnes</span><h1>Quelle taille de cafetière italienne choisir ?</h1><p>Le nombre de “tasses” n’est pas un volume universel. Comparez d’abord les millilitres réellement documentés et choisissez la taille correspondant à votre préparation habituelle.</p></div></section><section class="section"><div class="container"><div class="guide-callout"><strong>Repère essentiel :</strong> chez Bialetti, “cup” désigne une petite tasse de café. Pourtant, une 4 tasses peut produire environ 150, 170 ou 185 ml selon la gamme. Le chiffre seul ne suffit donc pas.</div><div class="directory">${['2','4','6','10','12'].map(n=>`<a href="/capacites/cafetiere-italienne-${n}-tasses/">Cafetière italienne ${n} tasses <span>→</span></a>`).join('')}</div></div></section>`
};

export const capacityPages={
 'cafetiere-italienne-2-tasses':{
  title:'Cafetière italienne 2 tasses : quel volume choisir ?',
  description:'Une moka 2 tasses produit environ 85 à 100 ml selon le modèle. Volumes réels, induction et modèles à vérifier avant achat.',
  canonical:'/capacites/cafetiere-italienne-2-tasses/',
  body:wrap('Cafetière italienne 2 tasses : quel volume choisir ?','Le petit format paraît simple, mais c’est celui où les écarts de volume et de diamètre comptent le plus — surtout sur induction.','Capacité · 2 tasses',`
<section class="guide-answer"><span class="eyebrow">Réponse courte</span><h2>Une 2 tasses correspond plutôt à 85–100 ml sur les modèles Bialetti documentés</h2><p>La Moka Express 2 tasses est donnée autour de <strong>90 ml</strong>, la Venus 2 tasses autour de <strong>85 ml</strong> et la Moka Induction 2 tasses autour de <strong>100 ml</strong>. Cela montre pourquoi “2 tasses” ne doit pas être converti automatiquement en deux personnes ou en deux mugs.</p></section>
<section><h2>Le vrai choix se fait entre volume et plaque</h2><div class="table-wrap"><table class="guide-table"><thead><tr><th>Modèle</th><th>Volume approximatif</th><th>Induction</th><th>Base</th></tr></thead><tbody><tr><td>Moka Express 2</td><td>90 ml</td><td>Non directement</td><td>~8 cm</td></tr><tr><td>Venus 2</td><td>85 ml</td><td>Non</td><td>~8 cm</td></tr><tr><td>Moka Induction 2</td><td>100 ml</td><td>Oui, si détectée</td><td>~9,5 cm</td></tr><tr><td>Brikka 2</td><td>90 ml</td><td>version classique : non</td><td>~8,6 cm</td></tr></tbody></table></div></section>
<section><h2>Sur induction, le petit diamètre devient le critère n°1</h2><p>Une cafetière peut avoir une base magnétique et rester trop petite pour être détectée par certaines plaques. Bialetti demande explicitement de vérifier le diamètre minimal accepté pour sa Moka Induction. La Venus 2 tasses, elle, est directement indiquée comme <strong>non compatible induction</strong>.</p><p>Si votre plaque est votre première contrainte, voyez le <a class="text-link" href="/comparatifs/cafetiere-italienne-induction/">comparatif induction</a> et le <a class="text-link" href="/guides/cafetiere-italienne-induction-compatibilite/">guide de compatibilité</a>.</p></section>
<section><h2>Quand 2 tasses est la bonne taille</h2><p>Choisissez ce format si votre quantité habituelle se situe réellement autour d’un petit café moka de 85 à 100 ml. Si vous avez régulièrement besoin de davantage, une 4 tasses évite de multiplier les préparations. Inversement, prendre une grande moka “pour avoir de la marge” n’est pas une bonne stratégie si vous comptez ensuite la sous-remplir.</p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/moka-express">Bialetti — Moka Express</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-venus-induction-copper">Bialetti — Venus</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-moka-induction-bi-layer-black">Bialetti — Moka Induction</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-brikka-new">Bialetti — Brikka</a></li></ul></section>`,`<h3>Repère</h3><p>Environ 85–100 ml selon la gamme. Sur induction, vérifiez surtout le diamètre.</p><span class="pill">Petit volume</span><span class="pill">Diamètre critique</span>`)
 },
 'cafetiere-italienne-4-tasses':{
  title:'Cafetière italienne 4 tasses : combien de ml ?',
  description:'Une moka 4 tasses produit environ 150 à 185 ml selon la gamme. Comparez Moka Express, Venus, Moka Induction et Brikka.',
  canonical:'/capacites/cafetiere-italienne-4-tasses/',
  body:wrap('Cafetière italienne 4 tasses : combien de ml ?','Le format 4 tasses est une zone intermédiaire très courante, mais son volume réel varie sensiblement selon la gamme.','Capacité · 4 tasses',`
<section class="guide-answer"><span class="eyebrow">Le chiffre utile</span><h2>Comptez environ 150 à 185 ml, pas quatre grandes tasses</h2><p>Bialetti documente environ <strong>185 ml</strong> pour la Moka Express 4 tasses, <strong>170 ml</strong> pour la Venus 4, et <strong>150 ml</strong> pour la Moka Induction 4 et la Brikka 4. Le nombre “4” décrit donc une catégorie de petites tasses moka, pas un volume fixe.</p></section>
<section><h2>Quatre gammes, quatre volumes proches mais non identiques</h2><div class="table-wrap"><table class="guide-table"><thead><tr><th>Modèle</th><th>Volume approximatif</th><th>Induction</th></tr></thead><tbody><tr><td>Moka Express 4</td><td>185 ml</td><td>Non directement</td></tr><tr><td>Venus 4</td><td>170 ml</td><td>Oui</td></tr><tr><td>Moka Induction 4</td><td>150 ml</td><td>Oui</td></tr><tr><td>Brikka 4</td><td>150 ml</td><td>selon version</td></tr></tbody></table></div></section>
<section><h2>Pourquoi ce format est souvent plus facile à choisir</h2><p>À 4 tasses, les principales familles Bialetti offrent déjà des bases plus larges que les très petits formats et plusieurs options natives pour l’induction. Le choix peut donc revenir à la construction souhaitée : aluminium classique, inox ou architecture bi-layer.</p><p><a class="text-link" href="/modeles/bialetti-moka-express/">Moka Express</a> · <a class="text-link" href="/modeles/bialetti-venus/">Venus</a> · <a class="text-link" href="/modeles/bialetti-moka-induction/">Moka Induction</a></p></section>
<section><h2>4 ou 6 tasses ?</h2><p>Ne raisonnez pas d’abord en nombre de personnes : comparez votre quantité habituelle avec les volumes. Si 150–185 ml vous laisse régulièrement trop court, les versions 6 tasses des mêmes familles montent autour de 235–280 ml. Si ce volume vous convient, passer à 6 uniquement “au cas où” n’apporte rien.</p><p><a class="text-link" href="/capacites/cafetiere-italienne-6-tasses/">Comparer avec 6 tasses →</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/moka-express">Bialetti — Moka Express</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-venus-induction-copper">Bialetti — Venus</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-moka-induction-bi-layer-black">Bialetti — Moka Induction</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-brikka-new">Bialetti — Brikka</a></li></ul></section>`,`<h3>Repère</h3><p>Environ 150–185 ml selon la gamme. Plusieurs options induction existent dans ce format.</p><span class="pill">150–185 ml</span><span class="pill">Format intermédiaire</span>`)
 },
 'cafetiere-italienne-6-tasses':{
  title:'Cafetière italienne 6 tasses : volume réel et usages',
  description:'Une moka 6 tasses produit environ 235 à 280 ml selon le modèle. Volumes, diamètre, induction et choix face à la 4 tasses.',
  canonical:'/capacites/cafetiere-italienne-6-tasses/',
  body:wrap('Cafetière italienne 6 tasses : volume réel et usages','Le format 6 tasses entre déjà dans une préparation généreuse : environ 235 à 280 ml sur les principales gammes Bialetti documentées.','Capacité · 6 tasses',`
<section class="guide-answer"><span class="eyebrow">Volume réel</span><h2>Une 6 tasses produit environ 235 à 280 ml selon le modèle</h2><p>La Moka Express 6 est donnée à environ <strong>250 ml</strong>, la Venus 6 à <strong>235 ml</strong> et la Moka Induction 6 à <strong>280 ml</strong>. Une même étiquette “6 tasses” peut donc représenter près de 45 ml d’écart entre deux gammes.</p></section>
<section><h2>Le format où la plaque devient généralement moins problématique</h2><p>Les bases sont plus larges qu’en 2 tasses : environ 10,5 cm pour la Moka Express 6 et la Venus 6, et 11,5 cm pour la Moka Induction 6. Cela ne dispense jamais de vérifier la plaque, mais le risque de non-détection lié à un très petit diamètre est moins central que sur les mini-formats.</p></section>
<section><h2>Choisir 6 tasses sans surdimensionner</h2><div class="table-wrap"><table class="guide-table"><thead><tr><th>Modèle</th><th>Volume approx.</th><th>Construction</th><th>Plaque</th></tr></thead><tbody><tr><td>Moka Express 6</td><td>250 ml</td><td>Aluminium</td><td>hors induction directe</td></tr><tr><td>Venus 6</td><td>235 ml</td><td>Inox</td><td>induction incluse</td></tr><tr><td>Moka Induction 6</td><td>280 ml</td><td>base bi-layer + haut aluminium</td><td>induction incluse</td></tr></tbody></table></div><p>La bonne question n’est donc pas “pour combien de personnes ?”, mais “est-ce qu’environ un quart de litre correspond à ma préparation habituelle ?”.</p></section>
<section><h2>Si 6 tasses est trop ou pas assez</h2><p>Pour une quantité habituelle plus proche de 150–185 ml, redescendez vers la <a class="text-link" href="/capacites/cafetiere-italienne-4-tasses/">4 tasses</a>. Si vous cherchez une grande préparation familiale ou de table, la <a class="text-link" href="/capacites/cafetiere-italienne-12-tasses/">12 tasses</a> change réellement d’échelle avec environ 595 ml sur la Moka Express.</p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/moka-express">Bialetti — Moka Express</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-venus-induction-copper">Bialetti — Venus</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-moka-induction-bi-layer-black">Bialetti — Moka Induction</a></li></ul></section>`,`<h3>Repère</h3><p>Environ 235–280 ml selon la gamme. Vérifiez surtout si ce volume correspond à votre usage régulier.</p><span class="pill">235–280 ml</span><span class="pill">Grand format courant</span>`)
 },
 'cafetiere-italienne-10-tasses':{
  title:'Cafetière italienne 10 tasses : une capacité moins standard qu’il n’y paraît',
  description:'La taille 10 tasses n’existe pas dans toutes les gammes. Différences entre Moka Express 9/12 tasses et Alessi 9090 10 tasses.',
  canonical:'/capacites/cafetiere-italienne-10-tasses/',
  body:wrap('Cafetière italienne 10 tasses : une capacité moins standard qu’il n’y paraît','À cette taille, le nombre inscrit sur le produit devient particulièrement trompeur : toutes les marques et gammes ne proposent pas un palier “10 tasses”.','Capacité · 10 tasses',`
<section class="guide-answer"><span class="eyebrow">Avant de chercher un modèle</span><h2>“10 tasses” n’est pas un palier universel</h2><p>La Moka Express actuellement listée par Bialetti passe de <strong>9 tasses (~410 ml)</strong> à <strong>12 tasses (~595 ml)</strong>. À l’inverse, l’<strong>Alessi 9090</strong> existe bien en version 10 tasses. Une requête “10 tasses” doit donc commencer par le volume attendu, pas par l’idée qu’un format identique existe dans toutes les gammes.</p></section>
<section><h2>Trois chemins possibles</h2><div class="comparison-picks"><div class="pick"><h3>Vous cherchez autour de 410 ml</h3><p>La Moka Express 9 tasses est le palier documenté juste en dessous dans la gamme classique actuelle.</p></div><div class="pick"><h3>Vous voulez réellement une référence 10 tasses</h3><p>L’Alessi 9090 propose une variante 10 cups, en inox et compatible induction.</p></div><div class="pick"><h3>Vous avez besoin de nettement plus</h3><p>La Moka Express 12 tasses atteint environ 595 ml et change sensiblement de catégorie de volume.</p></div></div></section>
<section><h2>Pourquoi il vaut mieux partir des millilitres</h2><p>Entre marques, “cup” n’est pas une unité réglementaire de capacité. Même à l’intérieur de Bialetti, les volumes des 2, 4 et 6 tasses varient selon Moka Express, Venus et Moka Induction. À 10 tasses, cette différence devient structurelle puisqu’une gamme peut ne pas proposer cette taille du tout.</p><p>Si votre besoin est d’abord quantitatif, comparez la <a class="text-link" href="/capacites/cafetiere-italienne-12-tasses/">12 tasses</a> et demandez-vous si ~595 ml n’est pas trop grand pour votre usage quotidien.</p></section>
<section><h2>Et l’induction ?</h2><p>La présence d’une grande capacité ne dit rien de la plaque. L’Alessi 9090 utilise un fond en acier magnétique compatible induction. Une Moka Express classique, y compris dans ses grandes tailles, n’est pas conçue pour l’induction directe.</p><p><a class="text-link" href="/modeles/alessi-9090/">Voir l’Alessi 9090</a> · <a class="text-link" href="/comparatifs/cafetiere-italienne-induction/">Comparer les modèles induction</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/moka-express">Bialetti — tailles Moka Express actuelles</a></li><li><a href="https://uk.alessi.com/products/9090-espresso-coffee-maker?variant=33749646147715">Alessi — 9090 10 cups</a></li><li><a href="https://alessi.com/products/9090-espresso-coffee-maker">Alessi — gamme 9090</a></li></ul></section>`,`<h3>Repère</h3><p>La Moka Express actuelle propose 9 puis 12 tasses ; la 9090 propose bien 10 tasses.</p><span class="pill">Taille non universelle</span>`)
 },
 'cafetiere-italienne-12-tasses':{
  title:'Cafetière italienne 12 tasses : volume et contraintes à connaître',
  description:'La Bialetti Moka Express 12 tasses produit environ 595 ml. Taille, encombrement et choix d’usage avant d’acheter une grande moka.',
  canonical:'/capacites/cafetiere-italienne-12-tasses/',
  body:wrap('Cafetière italienne 12 tasses : volume et contraintes à connaître','Une 12 tasses est une grande moka : la Moka Express documentée produit environ 595 ml et mesure nettement plus qu’une 4 ou 6 tasses.','Capacité · 12 tasses',`
<section class="guide-answer"><span class="eyebrow">Le vrai ordre de grandeur</span><h2>La Moka Express 12 tasses est donnée autour de 595 ml</h2><p>Bialetti indique environ <strong>595 ml</strong> de café préparé, pour une hauteur d’environ <strong>28,5 cm</strong> et une base d’environ <strong>13,5 cm</strong>. On n’est plus dans un simple format “un peu plus grand” que la 6 tasses : le volume est plus de deux fois supérieur à celui de la Moka Express 6.</p></section>
<section><h2>La bonne raison de choisir 12 tasses</h2><p>Ce format est cohérent si une préparation proche de 600 ml correspond régulièrement à votre besoin. Il l’est beaucoup moins si vous cherchez seulement une réserve de capacité pour des occasions ponctuelles : une moka est conçue pour être utilisée avec sa charge prévue, pas comme un récipient que l’on remplit arbitrairement à moitié.</p></section>
<section><h2>Avant achat, vérifiez trois contraintes</h2><ol class="decision-list"><li><strong>Le volume habituel :</strong> ~595 ml doit être proche de ce que vous préparez réellement.</li><li><strong>La place :</strong> environ 28,5 cm de haut sur la Moka Express 12 ; vérifiez rangement et manipulation.</li><li><strong>La plaque :</strong> la Moka Express classique n’est pas une cafetière induction directe, même dans cette grande taille.</li></ol></section>
<section><h2>12 tasses ou plusieurs préparations plus petites ?</h2><p>Si vos besoins alternent fortement — petit café en semaine, grande quantité rarement — deux tailles peuvent parfois être plus cohérentes qu’une seule très grande moka sous-remplie. Si votre usage se situe plutôt autour de 235–280 ml, la <a class="text-link" href="/capacites/cafetiere-italienne-6-tasses/">6 tasses</a> est une catégorie beaucoup plus proche.</p><p>Pour la méthode et le dosage, voyez aussi <a class="text-link" href="/guides/comment-utiliser-cafetiere-italienne/">comment utiliser une moka</a> et <a class="text-link" href="/guides/dosage-cafe-cafetiere-italienne/">le guide dosage</a>.</p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/moka-express">Bialetti — Moka Express, tailles et volumes</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-moka-induction-bi-layer-black">Bialetti — repère sur l’utilisation à la capacité prévue</a></li></ul></section>`,`<h3>Repère</h3><p>~595 ml, ~28,5 cm de haut, base ~13,5 cm sur la Moka Express 12.</p><span class="pill">Grande capacité</span><span class="pill">~595 ml</span>`)
 }
};