const sourceList=(items)=>`<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list">${items.map(([label,url,note])=>`<li><a class="text-link" href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>${note?` — ${note}`:''}</li>`).join('')}</ul></section>`;
const table=(heads,rows)=>`<div class="table-wrap"><table class="guide-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const shellBody=(slug,eyebrow,h1,lead,article,aside)=>`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · <a href="/comparatifs/">Comparatifs</a> · ${h1}</div><span class="eyebrow">${eyebrow}</span><h1>${h1}</h1><p>${lead}</p></div></section><div class="container template-grid comparison-layout"><article class="content-main">${article}</article><aside><div class="sidebar-card"><span class="eyebrow">Verdict rapide</span>${aside}</div></aside></div>`;

const generalSources=[
 ['Bialetti — utilisation de la Moka Express','https://bialetti-cookware.zendesk.com/hc/fr/articles/5416235346322-Comment-utiliser-la-Moka-Express','compatibilité hors induction et consignes officielles'],
 ['Bialetti — composition de la Moka Express','https://bialetti-cookware.zendesk.com/hc/fr/articles/5416208859282-Quelle-est-la-composition-de-la-Moka-Express','aluminium alimentaire'],
 ['Bialetti — Venus Induction','https://www.bialetti.co.nz/products/bialetti-venus-induction-copper','inox 18/10 et compatibilité induction selon taille'],
 ['Bialetti — Moka Induction','https://www.bialetti.co.nz/products/bialetti-moka-induction-bi-layer-black','chaudière bi-matière induction'],
 ['Alessi — 9090','https://alessi.com/fr/products/9090-espresso-coffee-maker','inox 18/10, fond magnétique, fermeture à levier']
];

const bestArticle=`
<section class="guide-answer"><span class="eyebrow">Notre réponse</span><h2>Il n’existe pas une seule “meilleure” moka : la plaque décide d’abord</h2><p>Pour une cuisine sans induction, la <strong>Bialetti Moka Express</strong> reste le choix le plus simple à recommander : construction très lisible, large choix de tailles et pièces faciles à identifier. Sur induction, la <strong>Bialetti Venus</strong> est plus rationnelle pour la plupart des foyers grâce à son corps en inox et à sa compatibilité documentée en 4 et 6 tasses. La <strong>Moka Induction</strong> vise ceux qui veulent conserver une partie de l’architecture et de l’aluminium de la moka classique avec une chaudière adaptée à l’induction. Enfin, l’<strong>Alessi 9090</strong> est un choix premium où la finition, le dessin et la fermeture à levier font réellement partie de la décision.</p><div class="guide-callout"><strong>Le critère à ne pas inverser :</strong> choisissez d’abord votre plaque et la quantité que vous préparez réellement. Le matériau, le style et le budget viennent ensuite.</div></section>
<section><h2>Notre sélection en un coup d’œil</h2>${table(['Modèle','À choisir si…','Plaque','Point à connaître'],[
 ['Bialetti Moka Express','vous voulez la référence classique et n’avez pas besoin d’induction','Gaz, électrique, vitrocéramique','aluminium ; pas d’induction directe'],
 ['Bialetti Venus','vous voulez un modèle inox polyvalent','Tous feux selon taille','la 2 tasses n’est pas documentée comme compatible induction'],
 ['Bialetti Moka Induction','vous aimez le geste classique mais cuisinez sur induction','Tous feux','chaudière acier/aluminium bi-layer'],
 ['Alessi 9090','le design, la fabrication et l’ouverture à levier comptent autant que la fonction','Induction incluse','positionnement nettement plus premium']
])}</section>
<section><h2>Pourquoi la Moka Express reste notre choix classique</h2><p>La Moka Express ne gagne pas parce qu’elle serait “meilleure en goût” par nature. Nous ne disposons pas d’un test comparatif propriétaire permettant une telle affirmation. Elle gagne sur un terrain plus concret : simplicité, architecture éprouvée, tailles nombreuses et documentation abondante. Bialetti confirme un corps en aluminium alimentaire et précise explicitement qu’elle n’est pas destinée à l’induction directe.</p><p>Elle convient particulièrement au lecteur qui veut comprendre exactement ce qu’il achète et qui utilise gaz, électrique ou vitrocéramique. Sur induction, elle cesse d’être notre premier choix : un adaptateur existe, mais acheter directement une moka conçue pour la plaque est généralement plus simple.</p></section>
<section><h2>Venus ou Moka Induction : deux bonnes réponses à l’induction</h2><div class="guide-split"><div><h3>Venus : la voie rationnelle</h3><p>La Venus mise sur l’inox 18/10 et une forme plus contemporaine. En 4 ou 6 tasses, Bialetti la documente pour l’induction. C’est notre choix par défaut lorsqu’on veut une moka simple, sans rechercher le dessin octogonal historique.</p></div><div><h3>Moka Induction : la voie hybride</h3><p>La Moka Induction associe une partie supérieure en aluminium à une chaudière bi-layer acier/aluminium. Elle est plus pertinente si l’on veut conserver l’identité visuelle et une partie des matériaux de la moka traditionnelle tout en utilisant l’induction.</p></div></div></section>
<section><h2>Quand l’Alessi 9090 devient le meilleur choix</h2><p>Le 9090 ne cherche pas le même rapport fonction/prix. Alessi le fabrique en inox 18/10, avec fond magnétique pour induction, bec anti-goutte et fermeture à levier. Il devient cohérent lorsque la cafetière reste visible, sert à table et que l’objet compte réellement. Si votre priorité est seulement de préparer du moka efficacement, la Venus est plus simple à justifier.</p></section>
<section><h2>La taille peut faire changer tout le classement</h2><p>Une “tasse” moka est petite et les volumes varient selon les gammes. Il est donc plus utile de vérifier le volume réel du modèle que de comparer uniquement les chiffres “2, 4 ou 6 tasses”. Une grande moka utilisée systématiquement pour une petite quantité n’est pas le bon raccourci : choisissez la capacité correspondant à votre usage habituel.</p><p>Pour aller plus loin, consultez notre <a class="text-link" href="/guides/comment-choisir-cafetiere-italienne/">guide de choix</a> et nos pages <a class="text-link" href="/capacites/">par capacité</a>.</p></section>
${sourceList(generalSources)}`;

const inductionSources=[generalSources[2],generalSources[3],['Bialetti — Brikka Induction','https://www.bialetti.co.nz/collections/all-stovetops-excludes-d-g/products/bialetti-brikka-induction','4 tasses, base bi-layer'],['Alessi — 9090','https://alessi.com/fr/products/9090-espresso-coffee-maker','fond magnétique et avertissement de diamètre sur petit format'],['Alessi — Vite','https://alessi.com/fr/products/vite-espresso-coffee-maker','modèle 2026, fond acier magnétique']];
const inductionArticle=`
<section class="guide-answer"><span class="eyebrow">Le choix le plus simple</span><h2>Pour l’induction, nous privilégions la Bialetti Venus en 4 ou 6 tasses</h2><p>Elle combine une construction inox 18/10, une compatibilité induction documentée sur les tailles qui nous intéressent le plus et une logique d’usage très directe. La <strong>Moka Induction</strong> est meilleure si vous voulez retrouver davantage l’esthétique de la Moka Express ; la <strong>Brikka Induction</strong> vise un café plus concentré avec son système spécifique ; l’<strong>Alessi 9090</strong> et la nouvelle <strong>Vite</strong> sont des choix design plus premium.</p></section>
<section><h2>Le vrai piège de l’induction n’est pas seulement le matériau</h2><p>Un fond doit être ferromagnétique, mais il doit aussi être détecté par votre plaque. Sur les petits modèles, le diamètre peut devenir le facteur bloquant. Alessi avertit par exemple, pour certaines tailles du 9090, de vérifier que la plaque peut s’activer avec un diamètre minimal de 90 mm. Bialetti précise de son côté que la Venus 2 tasses n’est pas adaptée à l’induction alors que les 4 et 6 tasses le sont.</p><div class="guide-callout">Avant d’acheter une petite moka induction, vérifiez le diamètre minimal accepté par votre zone de cuisson. “Compatible induction” sur la gamme ne signifie pas forcément que toutes les tailles le sont.</div></section>
<section><h2>Quatre profils, quatre choix</h2>${table(['Priorité','Choix','Pourquoi','Limite principale'],[
 ['Simplicité / inox','Bialetti Venus 4 ou 6 tasses','inox 18/10, gamme lisible, induction documentée','éviter la 2 tasses sur induction'],
 ['Look moka classique','Bialetti Moka Induction','partie supérieure aluminium et base bi-layer','construction hybride, pas 100 % inox'],
 ['Café plus concentré','Bialetti Brikka Induction 4 tasses','valve spécifique et base bi-layer','format plus spécialisé'],
 ['Objet premium','Alessi 9090','inox, levier, bec anti-goutte, design iconique','budget et diamètre à vérifier'],
 ['Design contemporain 2026','Alessi Vite','aluminium moulé + fond magnétique','moins de recul historique sur la gamme']
])}</section>
<section><h2>Pourquoi nous ne classons pas la Moka Express avec un adaptateur en tête</h2><p>Un disque adaptateur peut rendre une Moka Express utilisable sur induction. C’est pertinent si vous possédez déjà la cafetière. Pour un achat neuf, nous préférons recommander un modèle conçu nativement pour l’induction : moins de pièces, moins de variables de chauffe et une compatibilité plus facile à vérifier.</p><p>Pour le détail technique, voir <a class="text-link" href="/guides/cafetiere-italienne-induction-compatibilite/">notre guide de compatibilité induction</a>.</p></section>
${sourceList(inductionSources)}`;

const inoxSources=[generalSources[2],generalSources[4],['Alessi — Menhir','https://alessi.com/fr/products/menhir-espresso-coffee-maker','inox 18/10, chaudière magnétique, fabrication Italie']];
const inoxArticle=`
<section class="guide-answer"><span class="eyebrow">Notre sélection inox</span><h2>Venus pour le quotidien, 9090 ou Menhir si l’objet compte vraiment</h2><p>La <strong>Bialetti Venus</strong> est notre choix inox le plus facile à recommander pour un usage quotidien : construction documentée en inox 18/10, plusieurs tailles et compatibilité induction sur les formats 4 et 6 tasses. L’<strong>Alessi 9090</strong> monte en gamme avec sa fermeture à levier et son bec travaillé. Le <strong>Menhir</strong>, également en inox 18/10 avec chaudière magnétique, vise davantage l’objet artisanal et le design contemporain.</p></section>
<section><h2>Ce que “inox” change réellement</h2><p>Le matériau influence surtout la construction, l’entretien, l’aspect et la compatibilité de certaines bases. Nous n’utilisons pas l’inox comme raccourci pour affirmer qu’un café sera meilleur, plus sain ou plus aromatique : ces claims demanderaient des preuves que les fiches fabricants ne fournissent pas.</p><p>De même, <strong>inox ne veut pas automatiquement dire induction</strong>. Ce qui compte pour la plaque est la présence d’un fond magnétique adapté et son diamètre.</p></section>
<section><h2>Les trois modèles que nous retenons</h2><div class="guide-split"><div><h3>Bialetti Venus</h3><p>Le choix pragmatique : inox 18/10, poignée isolante et tailles 2, 4, 6 et 10 tasses selon les marchés. Pour induction, restez sur les tailles explicitement documentées comme compatibles.</p></div><div><h3>Alessi 9090</h3><p>Le choix premium iconique : inox 18/10, fond magnétique, fermeture à levier et bec anti-goutte. Il coûte davantage, mais les différences portent sur de vrais éléments de conception et pas uniquement sur une finition cosmétique.</p></div></div><div class="guide-callout"><strong>Alternative design :</strong> le Menhir d’Alessi est lui aussi en inox 18/10 avec chaudière en acier magnétique. Il est pertinent si vous cherchez une silhouette plus contemporaine et acceptez un positionnement premium.</div></section>
<section><h2>Notre verdict par usage</h2>${table(['Usage','Choix','Pourquoi'],[['Tous les jours','Venus','le moins de compromis fonctionnels'],['Induction + objet de table','9090','construction inox et design fonctionnel distinctif'],['Design contemporain / cadeau','Menhir','objet très affirmé, fabrication annoncée en Italie']])}</section>
${sourceList(inoxSources)}`;

const electricSources=[['Ariete — Moka Aroma 1368','https://www.ariete.eu/en/product/Moka-Aroma','6 tasses + adaptateur 4, arrêt automatique, maintien au chaud 30 min'],['Ariete — Moka Aroma Electric 1358','https://www.ariete.eu/en/product/Moka-Aroma-Elettrica-nera','2/4 tasses, 400 W, base 360°'],['Ariete — gamme moka électrique','https://a.ariete.net/catalog/moke-elettriche','gamme et modèles actuels'],['De’Longhi — Alicia EMK6 support','https://www.delonghi.com/fr-fr/s/EMK6','support fabricant du modèle 6 tasses']];
const electricArticle=`
<section class="guide-answer"><span class="eyebrow">Sans plaque de cuisson</span><h2>Ariete Moka Aroma 1368 pour plusieurs tasses ; 1358 pour un format plus compact</h2><p>Dans l’univers électrique actuel, Ariete documente encore clairement deux formats faciles à distinguer. La <strong>1368</strong> prépare jusqu’à 6 tasses avec adaptateur 4 tasses, arrêt automatique et maintien au chaud pendant 30 minutes. La <strong>1358</strong> vise 2 ou 4 tasses avec une base 360° et une puissance de 400 W. La <strong>De’Longhi Alicia EMK6</strong> reste documentée par le fabricant, mais sa distribution marchande peut varier : nous la traitons comme alternative plutôt que comme premier choix.</p></section>
<section><h2>Le bon critère ici n’est plus la plaque, mais l’autonomie</h2><p>Une moka électrique devient intéressante au bureau, en résidence secondaire ou dans une cuisine où l’on veut libérer la plaque. Le compromis est différent d’une moka classique : on gagne une base dédiée, parfois l’arrêt automatique et le maintien au chaud, mais on ajoute un appareil électrique, un cordon/base et davantage de composants.</p></section>
<section><h2>Deux Ariete pour deux usages très différents</h2>${table(['Modèle','Capacité annoncée','Fonctions utiles','Nous le choisirions pour…'],[['Ariete 1368','6 tasses + adaptateur 4','480 W, arrêt auto, maintien au chaud 30 min, base 360°','famille, bureau, plusieurs services'],['Ariete 1358','2/4 tasses','400 W, base 360°','1 à 2 personnes, encombrement moindre'],['De’Longhi Alicia EMK6','6 tasses','moka électrique documentée au support De’Longhi','alternative si disponible chez votre revendeur']])}</section>
<section><h2>Pourquoi nous n’inventons pas un classement au dixième de point</h2><p>Les différences vraiment vérifiables portent ici sur la capacité et les fonctions. Nous n’avons pas effectué de dégustation comparative propriétaire ni mesuré les températures de maintien au chaud. Les fiches fabricants suffisent pour comparer les fonctions ; elles ne suffisent pas pour déclarer qu’un modèle produit objectivement “le meilleur goût”.</p></section>
<section><h2>À qui nous déconseillons une moka électrique</h2><p>Si vous avez déjà une plaque adaptée et recherchez surtout la durabilité mécanique, une moka traditionnelle reste plus simple. Si vous voulez au contraire programmer ou automatiser davantage la préparation, vérifiez précisément les fonctions du modèle : “électrique” ne signifie pas automatiquement programmable.</p></section>
${sourceList(electricSources)}`;

const designSources=[generalSources[4],['Alessi — Vite','https://alessi.com/fr/products/vite-espresso-coffee-maker','nouveauté 2026, fonte d’aluminium, induction'],['Alessi — Pulcina','https://alessi.com/fr/products/pulcina-espresso-coffee-maker-1','design Michele De Lucchi'],['Alessi — La Cupola','https://alessi.com/fr/products/la-cupola-espresso-coffee-maker','design Aldo Rossi'],['Alessi — La Cupola induction','https://alessi.com/fr/products/la-cupola-espresso-coffee-maker-1','version induction 6 tasses']];
const designArticle=`
<section class="guide-answer"><span class="eyebrow">Design avant classement</span><h2>Le meilleur choix design dépend du langage que vous voulez dans la cuisine</h2><p>Nous ne classons pas ici six objets avec la même grille fonctionnelle. L’<strong>Alessi 9090</strong> est l’icône technique en inox ; la <strong>Vite</strong>, lancée en 2026, est la proposition industrielle contemporaine ; la <strong>Pulcina</strong> assume une silhouette sculpturale très expressive ; <strong>La Cupola</strong> transforme la moka en petite architecture de table.</p></section>
<section><h2>Quatre directions esthétiques réellement différentes</h2><div class="comparison-picks"><div class="pick"><span class="eyebrow">Icône fonctionnelle</span><h3>Alessi 9090</h3><p>Richard Sapper associe le dessin à des choix fonctionnels : base élargie, bec anti-goutte et fermeture à levier. C’est notre choix si vous voulez un objet premium sans sacrifier l’induction.</p></div><div class="pick"><span class="eyebrow">Nouveauté 2026</span><h3>Alessi Vite</h3><p>Sa chaudière reprend le vocabulaire d’une vis et son fond en acier magnétique la rend compatible induction. Elle apporte un design très actuel sans atteindre le prix du 9090.</p></div><div class="pick"><span class="eyebrow">Sculptural</span><h3>Alessi Pulcina</h3><p>Les volumes en gradins de Michele De Lucchi sont immédiatement reconnaissables. Des versions classiques et induction existent : il faut donc choisir la bonne référence, pas seulement le nom Pulcina.</p></div><div class="pick"><span class="eyebrow">Architecture</span><h3>La Cupola</h3><p>Le dessin d’Aldo Rossi est plus narratif que minimaliste. Une version induction distincte est aujourd’hui proposée, ce qui permet de conserver le concept dans une cuisine moderne.</p></div></div></section>
<section><h2>Notre choix selon le contexte</h2>${table(['Vous cherchez…','Notre choix','Raison'],[['Une icône durable et premium','9090','design historique + choix fonctionnels distinctifs'],['Un objet contemporain moins patrimonial','Vite','lancement 2026 et induction native'],['Une silhouette immédiatement reconnaissable','Pulcina','forme sculpturale et plusieurs tailles'],['Un objet architectural','La Cupola','dessin d’Aldo Rossi et version induction disponible']])}</section>
<section><h2>Ce que nous ne faisons pas sur cette page</h2><p>Nous ne transformons pas le design en pseudo-score scientifique. Nous ne supposons pas non plus qu’un objet plus cher produit un meilleur café. Le verdict porte sur le dessin, les matériaux documentés, la compatibilité avec votre cuisine et la cohérence de l’objet avec votre usage.</p></section>
${sourceList(designSources)}`;

const smallSources=[['Bialetti — Moka Express','https://bialetti-cookware.zendesk.com/hc/fr/articles/5416235346322-Comment-utiliser-la-Moka-Express','moka classique, non induction'],['Bialetti — Venus','https://www.bialetti.co.nz/products/bialetti-venus-induction-copper','2 tasses non induction ; 4/6 induction'],['Bialetti — Mini Express Induction','https://www.bialetti.co.nz/products/bialetti-mini-express-induction-2-cup-set','2 tasses, environ 90 ml, base bi-layer'],['Alessi — 9090','https://alessi.com/products/9090-espresso-coffee-maker','version 1 tasse, 7 cl, seuil de détection induction à vérifier'],['Alessi — Pulcina 1 tasse','https://alessi.com/fr/products/pulcina-espresso-coffee-maker-1','7 cl, format 1 tasse']];
const smallArticle=`
<section class="guide-answer"><span class="eyebrow">Petit format</span><h2>Pour une personne, choisissez d’abord le volume — puis vérifiez l’induction</h2><p>Sur gaz, électrique ou vitrocéramique, une petite <strong>Moka Express</strong> reste la solution la plus simple. Sur induction, la question devient plus délicate : les petits diamètres peuvent ne pas être détectés. La <strong>Mini Express Induction 2 tasses</strong> est une option spécifiquement documentée pour l’induction, tandis que la <strong>Venus 2 tasses</strong> ne l’est pas. Pour un objet premium extrêmement compact, l’<strong>Alessi 9090 1 tasse</strong> existe, mais Alessi demande de vérifier le seuil de détection de la plaque.</p></section>
<section><h2>Pourquoi “petite” ne veut pas dire la même chose pour tout le monde</h2><p>Une tasse moka n’est pas un mug. Un format annoncé 1, 2 ou 3 tasses produit une petite quantité de café concentré. Pour une personne qui boit un mug allongé, une 3 tasses peut donc être plus logique qu’une 1 tasse. À l’inverse, acheter une 6 tasses “pour avoir de la marge” n’est pas idéal si vous préparez presque toujours une petite quantité.</p></section>
<section><h2>Nos trois chemins</h2>${table(['Situation','Choix','Repère'],[['Une personne, pas d’induction','Moka Express 1 à 3 tasses','choisir selon le volume final voulu'],['Deux petites tasses sur induction','Mini Express Induction 2 tasses','environ 90 ml annoncés, base bi-layer'],['Très petit format premium','Alessi 9090 1 tasse','7 cl ; vérifier le diamètre minimal de détection']])}</section>
<section><h2>Le cas trompeur de la Venus 2 tasses</h2><p>La gamme Venus est souvent associée à l’induction, mais Bialetti précise que la version 2 tasses n’est pas adaptée à l’induction alors que les 4 et 6 tasses le sont. C’est exactement le type de détail qui justifie une page “petite cafetière” séparée du comparatif induction général.</p><div class="guide-callout">Si votre priorité absolue est un format 1 à 2 tasses sur induction, vérifiez le diamètre de base et la documentation de la taille exacte avant l’achat.</div></section>
<section><h2>Alternative design : Pulcina 1 tasse</h2><p>Alessi propose la Pulcina en format 1 tasse de 7 cl. Elle est pertinente si la petite taille et le design comptent davantage que l’induction ; il existe aussi des références Pulcina induction, mais elles ne correspondent pas nécessairement au même format.</p></section>
${sourceList(smallSources)}`;

export const comparisonPages={
 'meilleure-cafetiere-italienne':{title:'Meilleure cafetière italienne : laquelle choisir en 2026 ?',description:'Moka Express, Venus, Moka Induction ou Alessi 9090 : notre comparatif selon la plaque, la taille et l’usage réel.',canonical:'/comparatifs/meilleure-cafetiere-italienne/',body:shellBody('meilleure-cafetiere-italienne','Comparatif 2026','Meilleure cafetière italienne : laquelle choisir ?', 'Notre sélection privilégie les différences qui changent réellement la décision : plaque de cuisson, capacité, matériau et niveau de finition.',bestArticle,'<h3>Moka Express</h3><p>Notre choix classique hors induction.</p><h3>Venus</h3><p>Notre choix le plus rationnel sur induction.</p>')},
 'cafetiere-italienne-induction':{title:'Cafetière italienne induction : les modèles à privilégier en 2026',description:'Venus, Moka Induction, Brikka Induction ou Alessi : comparez les vraies compatibilités induction et les pièges de diamètre.',canonical:'/comparatifs/cafetiere-italienne-induction/',body:shellBody('cafetiere-italienne-induction','Comparatif induction','Cafetière italienne induction : laquelle choisir ?', 'Une moka induction doit être magnétique et suffisamment large pour être détectée par votre plaque. Nous comparons les options qui documentent clairement ces points.',inductionArticle,'<h3>Choix par défaut</h3><p><strong>Bialetti Venus 4 ou 6 tasses</strong></p><p>La 2 tasses est à éviter sur induction.</p>')},
 'cafetiere-italienne-inox':{title:'Cafetière italienne inox : notre sélection 2026',description:'Bialetti Venus, Alessi 9090 et Menhir : comparatif des cafetières moka en inox, sans promesses santé ou goût non prouvées.',canonical:'/comparatifs/cafetiere-italienne-inox/',body:shellBody('cafetiere-italienne-inox','Comparatif inox','Cafetière italienne inox : quels modèles choisir ?', 'Nous comparons ici la construction, la compatibilité et l’usage — pas des bénéfices santé ou gustatifs que les fabricants ne démontrent pas.',inoxArticle,'<h3>Quotidien</h3><p><strong>Bialetti Venus</strong></p><h3>Premium</h3><p><strong>Alessi 9090</strong></p>')},
 'cafetiere-italienne-electrique':{title:'Cafetière italienne électrique : notre sélection 2026',description:'Ariete Moka Aroma 1368, 1358 et De’Longhi Alicia : quelles moka électriques choisir selon la capacité et les fonctions ?',canonical:'/comparatifs/cafetiere-italienne-electrique/',body:shellBody('cafetiere-italienne-electrique','Comparatif électrique','Cafetière italienne électrique : laquelle choisir ?', 'Pour le bureau ou une cuisine sans plaque disponible, les critères changent : capacité, base, arrêt automatique et maintien au chaud deviennent prioritaires.',electricArticle,'<h3>Plusieurs tasses</h3><p><strong>Ariete 1368</strong></p><h3>Compact</h3><p><strong>Ariete 1358</strong></p>')},
 'cafetiere-italienne-design':{title:'Cafetière italienne design : 4 modèles qui ont une vraie identité',description:'9090, Vite, Pulcina ou La Cupola : quatre cafetières italiennes design avec des partis pris réellement différents.',canonical:'/comparatifs/cafetiere-italienne-design/',body:shellBody('cafetiere-italienne-design','Sélection design','Cafetière italienne design : quatre objets vraiment différents', 'Plutôt qu’un classement artificiel, nous comparons quatre langages de design et les contraintes concrètes qui les accompagnent.',designArticle,'<h3>Icône</h3><p><strong>Alessi 9090</strong></p><h3>Contemporain</h3><p><strong>Alessi Vite</strong></p>')},
 'petite-cafetiere-italienne':{title:'Petite cafetière italienne : les bons formats pour 1 à 2 personnes',description:'Petite moka pour une ou deux personnes : Moka Express, Mini Express Induction et Alessi 9090, avec attention au volume et au diamètre.',canonical:'/comparatifs/petite-cafetiere-italienne/',body:shellBody('petite-cafetiere-italienne','Petit format','Petite cafetière italienne : laquelle choisir ?', 'Une petite moka se choisit au volume réellement préparé. Sur induction, le diamètre minimal détectable devient aussi décisif.',smallArticle,'<h3>Hors induction</h3><p><strong>Moka Express</strong></p><h3>Induction 2 tasses</h3><p><strong>Mini Express Induction</strong></p>')}
};
