const wrap=(title,intro,badge,body,aside)=>`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · <a href="/modeles/">Modèles</a> · ${title}</div><span class="eyebrow">${badge}</span><h1>${title}</h1><p>${intro}</p></div></section><div class="container template-grid model-layout"><article class="content-main">${body}</article><aside><div class="sidebar-card"><span class="eyebrow">Repères</span>${aside}</div></aside></div>`;

export const modelPages={
 'bialetti-moka-express':{
  title:'Bialetti Moka Express : caractéristiques, tailles et limites',
  description:'Bialetti Moka Express : aluminium, compatibilité des plaques, tailles, pièces détachées et limites à connaître avant achat.',
  canonical:'/modeles/bialetti-moka-express/',
  body:wrap('Bialetti Moka Express : caractéristiques, tailles et limites','La moka historique reste très simple à comprendre : aluminium, nombreuses tailles et entretien basique. Sa limite décisive est tout aussi claire : pas d’induction directe.','Modèle · Bialetti',`
<section class="guide-answer"><span class="eyebrow">Verdict documentaire</span><h2>La bonne Moka Express est surtout la bonne taille, sur la bonne plaque</h2><p>La Moka Express convient si vous cherchez la moka classique de Bialetti et utilisez gaz, électrique ou vitrocéramique. Elle est fabriquée en aluminium alimentaire et conserve une architecture simple avec soupape de sécurité, entonnoir, filtre et joint remplaçables.</p><p>Elle devient moins rationnelle si votre cuisine est déjà entièrement à induction : un adaptateur existe, mais une Venus ou une Moka Induction évite cette couche supplémentaire.</p></section>
<section><h2>Ce que vous achetez réellement</h2><div class="table-wrap"><table class="guide-table"><tbody><tr><th>Matériau</th><td>Aluminium alimentaire</td></tr><tr><th>Plaques</th><td>Gaz, électrique, vitrocéramique</td></tr><tr><th>Induction directe</th><td>Non</td></tr><tr><th>Pièces courantes</th><td>Joint + filtre, entonnoir ; autres pièces selon marché</td></tr><tr><th>Point de vigilance</th><td>la taille annoncée correspond à de petites tasses moka, pas à des mugs</td></tr></tbody></table></div></section>
<section><h2>Pourquoi la simplicité compte ici</h2><p>La Moka Express ne demande pas de fonction spéciale pour être intéressante. Sa valeur tient justement au fait que les éléments essentiels sont faciles à identifier et que les pièces d’usure restent référencées. Bialetti publie par exemple des entonnoirs de remplacement avec dimensions selon la taille de la cafetière.</p><p>Cette simplicité n’autorise pas à lui attribuer un meilleur goût qu’une moka inox : nous n’avons pas de test propriétaire permettant une telle conclusion.</p></section>
<section><h2>Le choix de taille n’est pas secondaire</h2><p>Une moka se choisit pour la quantité préparée habituellement. Les “tasses” Bialetti renvoient à de petites portions de café. Si vous préparez presque toujours pour une personne, une grande Moka Express n’est pas automatiquement plus polyvalente : elle est conçue pour fonctionner avec sa charge prévue.</p><p><a class="text-link" href="/capacites/">Voir les capacités</a> · <a class="text-link" href="/guides/dosage-cafe-cafetiere-italienne/">Comprendre le dosage</a></p></section>
<section><h2>À choisir ou à éviter ?</h2><div class="guide-split"><div><h3>Choisissez-la si</h3><p>vous voulez la moka classique, votre plaque n’est pas une induction directe et vous appréciez un produit dont les consommables sont faciles à identifier.</p></div><div><h3>Regardez ailleurs si</h3><p>vous êtes sur induction, voulez absolument de l’inox ou cherchez une architecture explicitement pensée pour une autre plaque.</p></div></div><p><a class="text-link" href="/modeles/bialetti-venus/">Comparer avec la Venus</a> · <a class="text-link" href="/modeles/bialetti-moka-induction/">Voir la Moka Induction</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/moka-express">Bialetti — Moka Express</a></li><li><a href="https://www.bialetti.co.nz/collections/spare-parts">Bialetti — pièces détachées</a></li><li><a href="https://www.bialetti.co.nz/products/moka-express-dama-mini-express-break-funnels">Bialetti — entonnoirs et tailles</a></li></ul></section>`,`<h3>En bref</h3><p>Aluminium, hors induction directe, nombreuses tailles et pièces identifiables.</p><span class="pill">Aluminium</span><span class="pill">Classique</span>`)
 },
 'bialetti-venus':{
  title:'Bialetti Venus : inox, induction et tailles compatibles',
  description:'Bialetti Venus : inox 18/10, compatibilité induction selon la taille et différences pratiques face à la Moka Express.',
  canonical:'/modeles/bialetti-venus/',
  body:wrap('Bialetti Venus : inox, induction et tailles compatibles','La Venus est l’alternative inox de Bialetti, mais il faut vérifier la taille exacte : la 2 tasses fait exception sur induction.','Modèle · Bialetti',`
<section class="guide-answer"><span class="eyebrow">Le point décisif</span><h2>Venus est compatible induction… sauf la 2 tasses</h2><p>Bialetti documente la Venus en inox 18/10 comme compatible avec tous les feux dans ses tailles induction, avec une exception explicite : la <strong>Venus 2 tasses</strong> n’est pas adaptée à l’induction. Les versions 4 et 6 tasses le sont sur la fiche officielle consultée.</p><p>C’est la raison principale pour laquelle il ne faut jamais acheter “une Venus” en supposant que toute la gamme partage la même compatibilité.</p></section>
<section><h2>Ce que l’inox change concrètement</h2><p>La Venus utilise de l’inox alimentaire 18/10, avec une poignée annoncée résistante à la chaleur et un bec verseur conçu pour limiter les gouttes. L’intérieur de la chaudière est en inox non poli : Bialetti précise qu’il s’agit d’une finition sablée, pas d’un revêtement.</p><p>En revanche, l’inox n’est pas ici une preuve de meilleur goût ou de meilleure extraction. L’avantage documentable est surtout la construction et, selon la taille, l’accès à l’induction.</p></section>
<section><h2>Le tableau qui évite l’erreur d’achat</h2><div class="table-wrap"><table class="guide-table"><thead><tr><th>Taille</th><th>Induction</th><th>Lecture pratique</th></tr></thead><tbody><tr><td>2 tasses</td><td>Non</td><td>petit format, mais pas le bon choix pour une plaque induction</td></tr><tr><td>4 tasses</td><td>Oui</td><td>format compact cohérent pour l’induction</td></tr><tr><td>6 tasses</td><td>Oui</td><td>plus adapté aux préparations plus généreuses</td></tr></tbody></table></div><p>Quel que soit le format, vérifiez aussi que votre plaque accepte le diamètre du fond de la cafetière.</p></section>
<section><h2>Venus ou Moka Induction ?</h2><p>La Venus est la voie la plus directe si votre priorité est l’inox. La Moka Induction conserve davantage du langage matériel de la moka classique avec une chaudière bi-layer acier/aluminium et une partie supérieure en aluminium. Le bon choix dépend donc moins du logo que de votre préférence de construction.</p><p><a class="text-link" href="/modeles/bialetti-moka-induction/">Voir la Moka Induction</a> · <a class="text-link" href="/comparatifs/cafetiere-italienne-inox/">Comparer les moka inox</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/bialetti-venus-induction-copper">Bialetti — Venus</a></li><li><a href="https://www.bialetti.co.nz/collections/spare-parts">Bialetti — pièces Venus</a></li></ul></section>`,`<h3>À vérifier avant achat</h3><p>La taille exacte. 4 et 6 tasses sont documentées induction ; la 2 tasses ne l’est pas.</p><span class="pill">Inox 18/10</span><span class="pill">Induction selon taille</span>`)
 },
 'bialetti-moka-induction':{
  title:'Bialetti Moka Induction : fonctionnement, tailles et intérêt',
  description:'Bialetti Moka Induction : base bi-layer acier/aluminium, compatibilité induction, tailles et différence avec Venus.',
  canonical:'/modeles/bialetti-moka-induction/',
  body:wrap('Bialetti Moka Induction : fonctionnement, tailles et intérêt','La Moka Induction garde une partie de la construction de la moka classique tout en ajoutant une base adaptée aux plaques induction.','Modèle · Bialetti',`
<section class="guide-answer"><span class="eyebrow">Pourquoi elle existe</span><h2>Une moka hybride plutôt qu’une Venus déguisée</h2><p>La Moka Induction combine une base bi-layer en acier inoxydable et aluminium avec une partie supérieure en aluminium. Ce choix lui permet de fonctionner sur l’induction tout en restant visuellement et matériellement proche de la Moka Express.</p><p>Si vous voulez simplement une moka tout inox, la Venus est plus logique. Si vous voulez garder l’esprit Moka Express sur une plaque induction, la Moka Induction est plus cohérente.</p></section>
<section><h2>Construction et compatibilité</h2><div class="table-wrap"><table class="guide-table"><tbody><tr><th>Base</th><td>Bi-layer inox + aluminium</td></tr><tr><th>Partie supérieure</th><td>Aluminium</td></tr><tr><th>Plaques</th><td>Induction, gaz, électrique, céramique</td></tr><tr><th>Précaution</th><td>vérifier le diamètre minimal accepté par la plaque induction</td></tr></tbody></table></div></section>
<section><h2>Les tailles documentées sur la version actuelle</h2><p>Sur la Moka Induction Bi-Layer actuelle consultée, Bialetti indique environ <strong>100 ml en 2 tasses</strong>, <strong>150 ml en 4 tasses</strong> et <strong>280 ml en 6 tasses</strong>. Ces volumes restent approximatifs et dépendent de l’eau et du café utilisés.</p><p>Ce détail est utile parce qu’il montre pourquoi le simple nombre de “tasses” ne suffit pas pour comparer deux gammes. Si le volume est votre première contrainte, partez plutôt de nos <a class="text-link" href="/capacites/">pages par capacité</a>.</p></section>
<section><h2>Le vrai arbitrage : Moka Express, Moka Induction ou Venus</h2><div class="comparison-picks"><div class="pick"><h3>Moka Express</h3><p>La plus simple si vous n’avez pas besoin d’induction.</p></div><div class="pick"><h3>Moka Induction</h3><p>La plus proche de l’univers Moka Express pour une cuisine induction.</p></div><div class="pick"><h3>Venus</h3><p>La voie la plus logique si votre priorité est une construction inox.</p></div></div><p><a class="text-link" href="/comparatifs/cafetiere-italienne-induction/">Voir le comparatif induction</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/bialetti-moka-induction-bi-layer-black">Bialetti — Moka Induction Bi-Layer</a></li><li><a href="https://www.bialetti.co.nz/collections/stainless-stovetop">Bialetti — gamme induction</a></li></ul></section>`,`<h3>En bref</h3><p>Base acier/aluminium pour l’induction, partie supérieure en aluminium.</p><span class="pill">Bi-layer</span><span class="pill">Induction</span>`)
 },
 'alessi-9090':{
  title:'Alessi 9090 : design Richard Sapper, inox et induction',
  description:'Alessi 9090 : inox 18/10, fermeture à levier, induction, tailles et points à vérifier avant de choisir cette icône.',
  canonical:'/modeles/alessi-9090/',
  body:wrap('Alessi 9090 : design Richard Sapper, inox et induction','La 9090 n’est pas seulement une moka chère et dessinée : sa base élargie, son bec anti-goutte et sa fermeture à levier font partie du projet depuis son lancement.','Modèle · Alessi',`
<section class="guide-answer"><span class="eyebrow">Verdict documentaire</span><h2>Le surcoût achète surtout une conception particulière, pas une promesse de meilleur café</h2><p>Dessinée par Richard Sapper et produite depuis 1980, la 9090 combine inox 18/10, fond magnétique pour l’induction et plusieurs choix fonctionnels inhabituels : base élargie, bec anti-goutte et fermeture à levier.</p><p>Elle a donc du sens si vous valorisez réellement ces choix de conception et la fabrication de l’objet. Si votre priorité est uniquement de préparer une moka sur induction au coût le plus rationnel, des alternatives Bialetti seront plus directes.</p></section>
<section><h2>Ce qui la distingue d’une moka classique</h2><div class="guide-split"><div><h3>Fermeture à levier</h3><p>Alessi remplace la fermeture vissée classique par un mécanisme à levier permettant d’ouvrir la cafetière d’un geste.</p></div><div><h3>Base élargie</h3><p>Le dessin cherche aussi à améliorer la stabilité et l’exploitation de la chaleur, pas seulement à produire une silhouette reconnaissable.</p></div><div><h3>Bec anti-goutte</h3><p>Le bec fait partie des innovations fonctionnelles explicitement documentées par Alessi.</p></div><div><h3>Inox 18/10</h3><p>La construction la place dans un univers matériel différent des moka classiques en fonte d’aluminium.</p></div></div></section>
<section><h2>Induction : même la petite 9090 demande une vérification</h2><p>La référence 1 tasse est donnée pour <strong>7 cl</strong>, avec un diamètre de <strong>9,5 cm</strong>. Alessi demande explicitement de vérifier que la plaque induction peut s’activer avec un objet d’au moins <strong>90 mm</strong> de diamètre. C’est un bon exemple de la différence entre “fond magnétique” et “détection garantie sur toute plaque”.</p><p>La gamme actuelle affiche également des versions 3, 6 et 10 tasses. Vérifiez toujours la référence exacte avant achat.</p></section>
<section><h2>Pour qui la 9090 est cohérente</h2><p>Elle vise le lecteur pour qui l’objet de cuisine compte autant que sa fonction : matériau, mécanique d’ouverture, histoire du design et fabrication. Elle est moins rationnelle si vous cherchez uniquement l’option induction la plus simple ou la moins chère.</p><p><a class="text-link" href="/marques/alessi/">Comprendre la gamme Alessi</a> · <a class="text-link" href="/comparatifs/cafetiere-italienne-design/">Comparer les moka design</a> · <a class="text-link" href="/comparatifs/cafetiere-italienne-inox/">Comparer les moka inox</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://alessi.com/products/9090-espresso-coffee-maker">Alessi — 9090</a></li><li><a href="https://ch.alessi.com/fr/products/9090-espresso-coffee-maker">Alessi — 9090, fiche française</a></li></ul></section>`,`<h3>À retenir</h3><p>Inox 18/10, levier, bec anti-goutte, induction ; sur la 1 tasse, vérifiez la détection minimale de votre plaque.</p><span class="pill">Richard Sapper</span><span class="pill">Inox</span>`)
 }
};