const wrap=(title,intro,badge,body,aside)=>`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Accueil</a> · <a href="/modeles/">Modèles</a> · ${title}</div><span class="eyebrow">${badge}</span><h1>${title}</h1><p>${intro}</p></div></section><div class="container template-grid model-layout"><article class="content-main">${body}</article><aside><div class="sidebar-card"><span class="eyebrow">Repères</span>${aside}</div></aside></div>`;

export const modelPages={
 'bialetti-moka-express':{
  title:'Bialetti Moka Express : caractéristiques, tailles et limites',
  description:'Bialetti Moka Express : aluminium, compatibilité des plaques, tailles, pièces détachées et limites à connaître avant achat.',
  canonical:'/modeles/bialetti-moka-express/',
  body:wrap('Bialetti Moka Express : caractéristiques, tailles et limites','La moka historique reste très simple à comprendre : aluminium, nombreuses tailles et entretien basique. Sa limite décisive est tout aussi claire : pas d’induction directe.','Modèle · Bialetti',`
<section class="guide-answer"><span class="eyebrow">Verdict documentaire</span><h2>La bonne Moka Express est surtout la bonne taille, sur la bonne plaque</h2><p>La Moka Express convient si vous cherchez la moka classique de Bialetti et utilisez gaz, électrique ou vitrocéramique. Elle est fabriquée en aluminium alimentaire et conserve une architecture simple avec soupape de sécurité, entonnoir, filtre et joint remplaçables.</p><p>Elle devient moins rationnelle si votre cuisine est déjà entièrement à induction : un adaptateur existe, mais une Venus ou une Moka Induction évite cette couche supplémentaire.</p></section>
<section><h2>Ce que vous achetez réellement</h2><div class="table-wrap"><table class="guide-table"><tbody><tr><th>Matériau</th><td>Aluminium alimentaire</td></tr><tr><th>Plaques</th><td>Gaz, électrique, vitrocéramique</td></tr><tr><th>Induction directe</th><td>Non</td></tr><tr><th>Pièces courantes</th><td>Joint + filtre, entonnoir ; autres pièces selon marché</td></tr><tr><th>Point de vigilance</th><td>la taille annoncée correspond à de petites tasses moka, pas à des mugs</td></tr></tbody></table></div></section>
<section><h2>Pourquoi la simplicité compte ici</h2><p>La Moka Express ne demande pas de fonction spéciale pour être intéressante. Sa valeur tient justement au fait que les éléments essentiels sont faciles à identifier et que les pièces d’usure restent référencées. Bialetti publie par exemple des entonnoirs de remplacement avec dimensions selon la taille de la cafetière.</p><p>Cette simplicité n’autorise pas à lui attribuer un meilleur goût qu’une moka inox : nous n’avons pas de test propriétaire permettant une telle conclusion.</p></section>
<section><h2>Le choix de taille n’est pas secondaire</h2><p>Une moka se choisit pour la quantité préparée habituellement. Les “tasses” Bialetti renvoient à de petites portions de café. Si vous préparez presque toujours pour une personne, une grande Moka Express n’est pas automatiquement plus polyvalente : elle est conçue pour fonctionner avec sa charge prévue.</p><p><a class="text-link" href="/capacites/">Voir les capacités</a> · <a class="text-link" href="/guides/dosage-cafe-cafetiere-italienne/">Comprendre le dosage</a></p></section>
<section><h2>À choisir ou à éviter ?</h2><div class="guide-split"><div><h3>Choisissez-la si</h3><p>vous voulez la moka classique, votre plaque n’est pas une induction directe et vous appréciez un produit dont les consommables sont faciles à identifier.</p></div><div><h3>Regardez ailleurs si</h3><p>vous êtes sur induction, voulez absolument de l’inox ou cherchez une architecture explicitement pensée pour une autre plaque.</p></div></div><p><a class="text-link" href="/modeles/bialetti-venus/">Comparer avec la Venus</a> · <a class="text-link" href="/modeles/bialetti-moka-induction/">Voir la Moka Induction</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/moka-express">Bialetti — Moka Express</a></li><li><a href="https://www.bialetti.co.nz/collections/spare-parts">Bialetti — pièces détachées</a></li><li><a href="https://www.bialetti.co.nz/products/moka-express-dama-mini-express-break-funnels">Bialetti — entonnoirs et tailles</a></li></ul></section>`,`<h3>En bref</h3><p>Aluminium, hors induction directe, nombreuses tailles et pièces identifiables.</p><span class="pill">Aluminium</span><span class="pill">Classique</span>`)
 },
 'bialetti-venus':{
  title:'Bialetti Venus : inox, induction et tailles compatibles',
  description:'Bialetti Venus : inox 18/10, compatibilité induction selon la taille et différences pratiques face à la Moka Express.',
  canonical:'/modeles/bialetti-venus/',
  body:wrap('Bialetti Venus : inox, induction et tailles compatibles','La Venus est l’alternative inox de Bialetti, mais il faut vérifier la taille exacte : la 2 tasses fait exception sur induction.','Modèle · Bialetti',`
<section class="guide-answer"><span class="eyebrow">Le point décisif</span><h2>Venus est compatible induction… sauf la 2 tasses</h2><p>Bialetti documente la Venus en inox 18/10 comme compatible avec tous les feux dans ses tailles induction, avec une exception explicite : la <strong>Venus 2 tasses</strong> n’est pas adaptée à l’induction. Les versions 4 et 6 tasses le sont sur la fiche officielle consultée.</p><p>C’est la raison principale pour laquelle il ne faut jamais acheter “une Venus” en supposant que toute la gamme partage la même compatibilité.</p></section>
<section><h2>Ce que l’inox change concrètement</h2><p>La Venus utilise de l’inox alimentaire 18/10, avec une poignée annoncée résistante à la chaleur et un bec verseur conçu pour limiter les gouttes. L’intérieur de la chaudière est en inox non poli : Bialetti précise qu’il s’agit d’une finition sablée, pas d’un revêtement.</p><p>En revanche, l’inox n’est pas ici une preuve de meilleur goût ou de meilleure extraction. L’avantage documentable est surtout la construction et, selon la taille, l’accès à l’induction.</p></section>
<section><h2>Le tableau qui évite l’erreur d’achat</h2><div class="table-wrap"><table class="guide-table"><thead><tr><th>Taille</th><th>Induction</th><th>Lecture pratique</th></tr></thead><tbody><tr><td>2 tasses</td><td>Non</td><td>petit format, mais pas le bon choix pour une plaque induction</td></tr><tr><td>4 tasses</td><td>Oui</td><td>format compact cohérent pour l’induction</td></tr><tr><td>6 tasses</td><td>Oui</td><td>plus adapté aux préparations plus généreuses</td></tr></tbody></table></div><p>Quel que soit le format, vérifiez aussi que votre plaque accepte le diamètre du fond de la cafetière.</p></section>
<section><h2>Venus ou Moka Induction ?</h2><p>La Venus est la voie la plus directe si votre priorité est l’inox. La Moka Induction conserve davantage du langage matériel de la moka classique avec une chaudière bi-layer acier/aluminium et une partie supérieure en aluminium. Le bon choix dépend donc moins du logo que de votre préférence de construction.</p><p><a class="text-link" href="/modeles/bialetti-moka-induction/">Voir la Moka Induction</a> · <a class="text-link" href="/comparatifs/cafetiere-italienne-inox/">Comparer les moka inox</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/bialetti-venus-induction-copper">Bialetti — Venus</a></li><li><a href="https://www.bialetti.co.nz/collections/spare-parts">Bialetti — pièces Venus</a></li></ul></section>`,`<h3>À vérifier avant achat</h3><p>La taille exacte. 4 et 6 tasses sont documentées induction ; la 2 tasses ne l’est pas.</p><span class="pill">Inox 18/10</span><span class="pill">Induction selon taille</span>`)
 },
 'bialetti-moka-induction':{
  title:'Bialetti Moka Induction : fonctionnement, tailles et intérêt',
  description:'Bialetti Moka Induction : base bi-layer acier/aluminium, compatibilité induction, tailles et différence avec Venus.',
  canonical:'/modeles/bialetti-moka-induction/',
  body:wrap('Bialetti Moka Induction : fonctionnement, tailles et intérêt','La Moka Induction garde une partie de la construction de la moka classique tout en ajoutant une base adaptée aux plaques induction.','Modèle · Bialetti',`
<section class="guide-answer"><span class="eyebrow">Pourquoi elle existe</span><h2>Une moka hybride plutôt qu’une Venus déguisée</h2><p>La Moka Induction combine une base bi-layer en acier inoxydable et aluminium avec une partie supérieure en aluminium. Ce choix lui permet de fonctionner sur l’induction tout en restant visuellement et matériellement proche de la Moka Express.</p><p>Si vous voulez simplement une moka tout inox, la Venus est plus logique. Si vous voulez garder l’esprit Moka Express sur une plaque induction, la Moka Induction est plus cohérente.</p></section>
<section><h2>Construction et compatibilité</h2><div class="table-wrap"><table class="guide-table"><tbody><tr><th>Base</th><td>Bi-layer inox + aluminium</td></tr><tr><th>Partie supérieure</th><td>Aluminium</td></tr><tr><th>Plaques</th><td>Induction, gaz, électrique, céramique</td></tr><tr><th>Précaution</th><td>vérifier le diamètre minimal accepté par la plaque induction</td></tr></tbody></table></div></section>
<section><h2>Les tailles documentées sur la version actuelle</h2><p>Sur la Moka Induction Bi-Layer actuelle consultée, Bialetti indique environ <strong>100 ml en 2 tasses</strong>, <strong>150 ml en 4 tasses</strong> et <strong>280 ml en 6 tasses</strong>. Ces volumes restent approximatifs et dépendent de l’eau et du café utilisés.</p><p>Ce détail est utile parce qu’il montre pourquoi le simple nombre de “tasses” ne suffit pas pour comparer deux gammes. Si le volume est votre première contrainte, partez plutôt de nos <a class="text-link" href="/capacites/">pages par capacité</a>.</p></section>
<section><h2>Le vrai arbitrage : Moka Express, Moka Induction ou Venus</h2><div class="comparison-picks"><div class="pick"><h3>Moka Express</h3><p>La plus simple si vous n’avez pas besoin d’induction.</p></div><div class="pick"><h3>Moka Induction</h3><p>La plus proche de l’univers Moka Express pour une cuisine induction.</p></div><div class="pick"><h3>Venus</h3><p>La voie la plus logique si votre priorité est une construction inox.</p></div></div><p><a class="text-link" href="/comparatifs/cafetiere-italienne-induction/">Voir le comparatif induction</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/bialetti-moka-induction-bi-layer-black">Bialetti — Moka Induction Bi-Layer</a></li><li><a href="https://www.bialetti.co.nz/collections/stainless-stovetop">Bialetti — gamme induction</a></li></ul></section>`,`<h3>En bref</h3><p>Base acier/aluminium pour l’induction, partie supérieure en aluminium.</p><span class="pill">Bi-layer</span><span class="pill">Induction</span>`)
 },
 'bialetti-brikka':{
  title:"Bialetti Brikka : 2 ou 4 tasses, induction, valve et pièces",
  description:"Bialetti Brikka : versions 2 et 4 tasses, valve, dosage d’eau, induction, entretien et pièces par génération.",
  canonical:'/modeles/bialetti-brikka/',
  body:wrap("Bialetti Brikka : 2 ou 4 tasses, induction, valve et pièces","La Brikka n’est pas simplement une Moka Express « avec crema » : sa valve, sa quantité d’eau mesurée et ses variantes classique/induction changent réellement la manière de la choisir et de l’utiliser.","Modèle · Bialetti",`
<section class="guide-answer"><span class="eyebrow">Premier choix</span><h2>Brikka classique ou Brikka Induction : commencez par la plaque et le volume</h2><p>La Brikka classique actuelle est en aluminium et n’est pas compatible directement avec l’induction. La Brikka Induction vérifiée utilise au contraire une base bi-layer et fonctionne sur induction.</p><div class="table-wrap"><table class="guide-table"><thead><tr><th>Version vérifiée</th><th>Café préparé approx.</th><th>Base approx.</th><th>Eau à mesurer</th><th>Induction directe</th></tr></thead><tbody><tr><td>Brikka classique 2 tasses</td><td>≈ 90 ml</td><td>≈ 8,6 cm</td><td>120 ml</td><td>Non</td></tr><tr><td>Brikka classique 4 tasses</td><td>≈ 150 ml</td><td>≈ 10,2 cm</td><td>170 ml</td><td>Non</td></tr><tr><td>Brikka Induction 4 tasses</td><td>≈ 160 ml</td><td>≈ 11,5 cm</td><td>170 ml</td><td>Oui</td></tr></tbody></table></div><p>Le nombre de tasses ne suffit donc pas : une 4 tasses classique et une 4 tasses Induction n’ont ni la même construction ni exactement le même rendement documenté.</p><p><a class="text-link" href="/capacites/">Comparer les volumes réels →</a> · <a class="text-link" href="/guides/cafetiere-italienne-induction-compatibilite/">Vérifier votre plaque →</a></p></section>

<section><h2>La valve est la vraie différence avec la Moka Express — pas une garantie d’espresso</h2><p>Bialetti décrit la Brikka comme une moka équipée d’une valve spécifique destinée à produire un café plus concentré et une mousse dorée plus marquée qu’avec la Moka Express. C’est le cœur du produit et la raison principale de la choisir.</p><p>Il faut toutefois garder le claim à sa juste place : cette page ne transforme pas le mot « crema » en promesse d’une crema identique à celle d’une machine espresso, ni en résultat visuel garanti à chaque préparation. Les retours utilisateurs montrent justement que la mousse obtenue peut varier selon la préparation et l’exemplaire.</p><div class="guide-callout"><strong>Bon critère d’achat :</strong> choisissez la Brikka si vous voulez réellement sa logique de valve et un café plus concentré. Ne la choisissez pas uniquement parce que le mot « crema » apparaît dans la fiche produit.</div><p><a class="text-link" href="/modeles/bialetti-moka-express/">Comparer avec la Moka Express →</a></p></section>

<section><h2>120 ou 170 ml d’eau : sur Brikka, la quantité mesurée est un hard gate</h2><p>Les instructions actuelles Bialetti demandent d’utiliser le gobelet doseur fourni : <strong>120 ml d’eau pour la Brikka classique 2 tasses</strong> et <strong>170 ml pour la classique 4 tasses</strong>. La Brikka Induction 4 tasses vérifiée utilise elle aussi 170 ml.</p><p>C’est une différence importante avec les conseils génériques souvent associés aux moka. Pour ces références Brikka, il ne faut pas remplacer arbitrairement la recette fabricant par « remplir jusqu’à la soupape ». Bialetti précise que la quantité d’eau est importante pour le fonctionnement optimal de la Brikka.</p><p>La marque recommande aussi une mouture medium-fine, un remplissage libre du funnel sans tassage et une chauffe faible à moyenne.</p><p><a class="text-link" href="/guides/dosage-cafe-cafetiere-italienne/">Comprendre le dosage d’une moka →</a> · <a class="text-link" href="/guides/mouture-cafetiere-italienne/">Choisir la mouture →</a></p></section>

<section><h2>Induction : adaptateur pour la classique ou Brikka Induction bi-layer ?</h2><p>La Brikka aluminium 2/4 tasses ne fonctionne pas directement sur induction. Bialetti indique qu’un adaptateur induction peut être utilisé avec ces modèles classiques.</p><p>La Brikka Induction 4 tasses vérifiée est une autre construction : extérieur de base en acier inoxydable, intérieur aluminium, diamètre de base autour de 11,5 cm et compatibilité directe induction, gaz, électrique et céramique.</p><p>Si votre objectif est de conserver la Brikka classique, l’adaptateur ajoute un intermédiaire. Si vous voulez éviter cet accessoire, la Brikka Induction est la route directement conçue pour la plaque — tout en restant à vérifier avec le diamètre minimal détecté par votre foyer.</p><p><a class="text-link" href="/accessoires/adaptateur-induction-cafetiere-italienne/">Voir l’adaptateur induction →</a> · <a class="text-link" href="/modeles/bialetti-moka-induction/">Comparer avec la Moka Induction →</a></p></section>

<section><h2>Pièces : 2024 change l’entonnoir, et le pack joint/filtre ne suit pas le nom de la taille</h2><p>Bialetti sépare explicitement les funnels des Brikka produites de <strong>2016 à 2023</strong> et ceux du <strong>modèle actuel 2024</strong>. Le diamètre reste identique dans les tailles vérifiées, mais la longueur change :</p><div class="table-wrap"><table class="guide-table"><thead><tr><th>Taille Brikka</th><th>Funnel 2016–2023</th><th>Funnel actuel 2024</th></tr></thead><tbody><tr><td>2 tasses</td><td>Ø 60 × 60 mm</td><td>Ø 60 × 69 mm</td></tr><tr><td>4 tasses</td><td>Ø 65 × 85 mm</td><td>Ø 65 × 93 mm</td></tr></tbody></table></div><p>Le mapping des joints et filtres est encore plus contre-intuitif : pour une <strong>Brikka 2 tasses</strong>, Bialetti demande le pack correspondant à la <strong>Moka 3 tasses</strong> ; pour une <strong>Brikka 4 tasses</strong>, le pack correspondant à la <strong>Moka 6 tasses</strong>.</p><div class="guide-callout"><strong>Avant de commander :</strong> identifiez la génération, la taille Brikka et la pièce exacte. Le nombre de tasses imprimé sur la cafetière ne suffit pas à choisir le nom du pack de remplacement.</div><p><a class="text-link" href="/accessoires/pieces-detachees-bialetti/">Identifier les pièces Bialetti →</a></p></section>

<section><h2>Entretien : lavage manuel et trois premières préparations à sacrifier</h2><p>Les consignes actuelles indiquent de laver la Brikka à la main et de ne pas la passer au lave-vaisselle. Bialetti recommande également de jeter les trois premières préparations avant l’usage normal et de ne pas utiliser la poignée comme levier pour dévisser la cafetière.</p><p>Pendant la préparation, la marque recommande une chauffe faible à moyenne et de retirer la cafetière du feu lorsqu’elle est prête, sans la laisser bouillir ni la pousser systématiquement à pleine puissance.</p><p><a class="text-link" href="/guides/nettoyer-cafetiere-italienne/">Voir le guide de nettoyage →</a></p></section>

<section><h2>Brikka, Moka Express ou Moka Induction : quel compromis cherchez-vous ?</h2><div class="comparison-picks"><div class="pick"><h3>Brikka</h3><p>Pour qui valorise la valve et accepte une quantité d’eau spécifique ainsi qu’une vérification plus fine des pièces.</p></div><div class="pick"><h3>Moka Express</h3><p>Pour une moka aluminium plus simple, sans objectif particulier de mousse Brikka.</p></div><div class="pick"><h3>Moka Induction</h3><p>Pour l’induction directe avec architecture bi-layer, sans acheter la Brikka pour sa valve.</p></div></div><p>Si votre priorité absolue est la simplicité du rituel, la Brikka peut être une complexité inutile. Si votre priorité est précisément son fonctionnement à valve et que vous acceptez son protocole, elle devient une proposition réellement distincte.</p><p><a class="text-link" href="/marques/bialetti/">Revenir à la gamme Bialetti →</a></p></section>

<section class="guide-sources" id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/bialetti-brikka-new">Bialetti — Brikka actuelle : tailles, volumes, eau, plaques et entretien</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-brikka-induction">Bialetti — Brikka Induction 4 tasses : construction, volume, base et protocole</a></li><li><a href="https://www.bialetti.co.nz/products/funnel-new-brikka">Bialetti — funnel Brikka 2016–2023</a></li><li><a href="https://www.bialetti.co.nz/products/funnel-brikka-2016-to-current-models-only-copy">Bialetti — funnel Brikka modèle actuel 2024</a></li><li><a href="https://www.bialetti.co.nz/products/moka-express-dama-mini-express-break-ring-filter-pack">Bialetti — compatibilité rings & filters Brikka</a></li><li><a href="https://www.interismo.be/fr-BE/bialetti/cafetieres-italiennes-brikka">Interismo Belgique — variantes Brikka actuellement référencées</a></li></ul></section>
`,`
<p><strong>Classique</strong><br>2 / 4 tasses · aluminium</p><p><strong>Induction vérifiée</strong><br>4 tasses · base bi-layer</p><p><strong>Volumes préparés</strong><br>≈ 90 / 150 / 160 ml</p><p><strong>Point clé</strong><br>120 ou 170 ml d’eau mesurée</p><span class="pill">Valve Brikka</span><span class="pill">Lavage manuel</span>
`)
 },
 'bialetti-mini-express':{
  title:"Bialetti Mini Express : 2 tasses, induction, volume et pièces",
  description:"Bialetti Mini Express : service direct dans deux tasses, volume réel, induction, entretien et pièces.",
  canonical:'/modeles/bialetti-mini-express/',
  body:wrap("Bialetti Mini Express : 2 tasses, induction, volume et pièces","La Mini Express ne cherche pas d’abord à changer le goût d’une moka : elle change le service. Le café sort directement par deux becs vers deux petites tasses, avec un rendement d’environ 90 ml au total sur les références vérifiées.","Modèle · Bialetti",`
<section class="guide-answer"><span class="eyebrow">Premier choix</span><h2>Mini Express classique ou Induction : commencez par la plaque</h2><p>Les deux références vérifiées préparent environ 90 ml au total, mais leur construction diffère nettement. La classique est en aluminium et n’est pas compatible directement avec l’induction. La Mini Express Induction utilise une base bi-layer inox/aluminium compatible avec l’induction.</p><div class="table-wrap"><table class="guide-table"><thead><tr><th>Version vérifiée</th><th>Volume préparé approx.</th><th>Base approx.</th><th>Construction</th><th>Induction directe</th></tr></thead><tbody><tr><td>Mini Express classique 2 tasses</td><td>≈ 90 ml</td><td>≈ 8,0 cm</td><td>Aluminium</td><td>Non</td></tr><tr><td>Mini Express Induction 2 tasses</td><td>≈ 90 ml</td><td>≈ 9,2–9,5 cm selon source régionale</td><td>Bi-layer inox / aluminium</td><td>Oui</td></tr></tbody></table></div><p>Sur induction, le mot « compatible » ne suffit pas : le diamètre minimal détecté par votre plaque reste à vérifier.</p><p><a class="text-link" href="/guides/cafetiere-italienne-induction-compatibilite/">Vérifier votre plaque →</a> · <a class="text-link" href="/accessoires/adaptateur-induction-cafetiere-italienne/">Voir l’adaptateur pour la classique →</a></p></section>

<section><h2>Ce que la Mini Express change vraiment : le café arrive directement dans deux tasses</h2><p>Le différenciateur utile est mécanique et pratique : il n’y a pas de chambre supérieure servant ensuite à verser le café. Deux sorties dirigent directement la préparation vers les tasses placées sous les becs.</p><p>La plaque support en aluminium est chauffée pendant la préparation et contribue à tempérer les petites tasses. C’est un bénéfice de service, pas une preuve que le café est meilleur qu’avec une Moka Express.</p><div class="guide-callout"><strong>Bon critère d’achat :</strong> choisissez la Mini Express si le service direct dans deux petites tasses compte réellement dans votre rituel. Si ce détail vous est indifférent, une moka classique est souvent plus simple à comparer et à remplacer.</div><p><a class="text-link" href="/modeles/bialetti-moka-express/">Comparer avec la Moka Express →</a></p></section>

<section><h2>« 2 tasses » signifie ici environ 90 ml au total</h2><p>Les références classique et Induction vérifiées sont toutes deux annoncées autour de <strong>90 ml de café préparé</strong>. Il faut donc lire « 2 tasses » comme deux petits services moka/espresso-style, pas comme deux grandes tasses de café.</p><p>Ce point est déterminant avant l’achat : si vous voulez environ 90 ml par personne, la Mini Express 2 tasses sera trop petite. Si vous voulez partager un petit service entre deux personnes ou boire vous-même deux petits cafés, le format devient cohérent.</p><p><a class="text-link" href="/capacites/">Comparer les volumes réels →</a></p></section>

<section><h2>Induction : la base est plus large, mais votre plaque doit encore la détecter</h2><p>La Mini Express Induction vérifiée combine un extérieur de base en acier inoxydable et un intérieur aluminium. Bialetti NZ indique une base d’environ 9,5 cm ; un distributeur européen spécialisé annonce environ 9,2 cm. Cette petite différence de mesure ne change pas la décision : vérifiez le seuil de détection indiqué par le fabricant de votre plaque.</p><p>La version classique aluminium, elle, ne fonctionne pas directement sur induction. Bialetti indique l’adaptateur comme solution si vous souhaitez conserver cette construction.</p><p><a class="text-link" href="/modeles/bialetti-moka-induction/">Comparer avec la Moka Induction →</a></p></section>

<section><h2>Les tasses ne sont pas systématiquement les mêmes selon le set</h2><p>La référence classique actuelle vérifiée chez Bialetti NZ est vendue sans tasses, alors que le set Mini Express Induction vérifié comprend deux tasses noires. D’autres éditions et distributeurs proposent aussi des ensembles avec tasses décorées.</p><p>Il faut donc vérifier le contenu exact de la référence achetée plutôt que déduire « Mini Express = toujours deux tasses incluses ». Bialetti précise par ailleurs que, si une tasse est perdue ou cassée, la plupart des petites tasses espresso adaptées à l’espace sous les becs peuvent convenir.</p></section>

<section><h2>Deux becs : ne transformez pas un signal utilisateur en garantie</h2><p>Des discussions récentes d’utilisateurs signalent parfois un débit déséquilibré entre les deux sorties ou des crachotements. Ce signal est utile parce qu’il correspond à une vraie anxiété d’usage, mais il ne permet pas de conclure que toutes les Mini Express répartissent mal le café.</p><p>La bonne lecture est donc prudente : le système est conçu pour servir deux tasses simultanément, sans promesse ici d’un partage 50/50 mesuré à chaque préparation.</p><div class="guide-callout"><strong>À éviter :</strong> acheter ce modèle en supposant qu’il garantit deux volumes strictement identiques à chaque service. Les sources fabricant décrivent le double service ; les retours communautaires montrent que l’expérience peut varier.</div></section>

<section><h2>Pièces : ce qui est documenté pour la classique ne doit pas être extrapolé à l’Induction</h2><p>Une boutique régionale Bialetti liste le kit joint + filtre pour cafetières aluminium 2 tasses comme compatible avec la Mini Express classique. Un guide spécialisé de pièces confirme que Mini Express partage certaines familles de joints et filtres avec les moka aluminium Bialetti selon la taille.</p><p>En revanche, le dossier actuel ne permet pas d’affirmer que ce même kit convient automatiquement à la Mini Express Induction. Avant de commander une pièce, vérifiez donc le modèle exact et les dimensions.</p><p><a class="text-link" href="/accessoires/pieces-detachees-bialetti/">Identifier les pièces Bialetti →</a></p></section>

<section><h2>Utilisation et entretien : le protocole reste celui d’une moka</h2><p>Pour les références actuelles vérifiées, Bialetti demande de remplir l’eau juste sous la soupape, d’ajouter le café moulu sans le tasser et d’utiliser une chauffe faible à moyenne. La cafetière doit être retirée du feu à la fin de la préparation.</p><p>Le lavage se fait à la main ; les fiches actuelles indiquent que la Mini Express n’est pas adaptée au lave-vaisselle et recommandent de jeter les trois premières préparations avant l’usage normal.</p><p><a class="text-link" href="/guides/dosage-cafe-cafetiere-italienne/">Dosage moka →</a> · <a class="text-link" href="/guides/mouture-cafetiere-italienne/">Choisir la mouture →</a> · <a class="text-link" href="/guides/nettoyer-cafetiere-italienne/">Nettoyage →</a></p></section>

<section><h2>Mini Express, Moka Express, Brikka ou Moka Induction ?</h2><div class="comparison-picks"><div class="pick"><h3>Mini Express</h3><p>Pour le petit volume et le plaisir du service direct dans deux tasses.</p></div><div class="pick"><h3>Moka Express</h3><p>Pour une moka classique plus conventionnelle avec chambre supérieure.</p></div><div class="pick"><h3>Brikka</h3><p>Pour qui cherche spécifiquement la valve et accepte son protocole dédié.</p></div><div class="pick"><h3>Moka Induction</h3><p>Pour l’induction directe sans besoin du double service Mini Express.</p></div></div><p>La Mini Express est cohérente quand son format de service est lui-même la raison d’achat. Si vous cherchez surtout plus de volume, une mécanique plus standard ou la logique Brikka, une autre fiche du cluster répond mieux à la décision.</p><p><a class="text-link" href="/modeles/bialetti-brikka/">Comparer avec la Brikka →</a> · <a class="text-link" href="/marques/bialetti/">Revenir à la gamme Bialetti →</a></p></section>

<section class="guide-sources" id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://www.bialetti.co.nz/products/bialetti-mini-express-black">Bialetti NZ — Mini Express classique : volume, construction, plaques et entretien</a></li><li><a href="https://www.bialetti.co.nz/products/bialetti-mini-express-induction-2-cup-set">Bialetti NZ — Mini Express Induction : volume, bi-layer et induction</a></li><li><a href="https://bialetti-shop.de/Espressokocher-Edelstahl-Induktion/mini-espress-induktion.html">Bialetti Shop DE — Mini Express Induction : base et set européen</a></li><li><a href="https://www.interismo.be/fr-BE/bialetti/mini-express">Interismo Belgique — Mini Express classique actuellement référencée</a></li><li><a href="https://bialetti.ru/catalog/komplektuyushchie/">Bialetti régional — compatibilité joint/filtre Mini Express classique 2 tasses</a></li><li><a href="https://brewitalia.com/pages/bialetti-spares-guide">Brew Italia — guide de compatibilité des pièces Bialetti</a></li></ul></section>
`,`
<p><strong>Format vérifié</strong><br>2 tasses · ≈90 ml total</p><p><strong>Classique</strong><br>Aluminium · hors induction directe</p><p><strong>Induction</strong><br>Base bi-layer · ≈9,2–9,5 cm</p><p><strong>Point clé</strong><br>Service direct dans deux tasses</p><span class="pill">Petit volume</span><span class="pill">Lavage manuel</span>
`)
 },
 'alessi-9090':{
  title:'Alessi 9090 : design Richard Sapper, inox et induction',
  description:'Alessi 9090 : inox 18/10, fermeture à levier, induction, tailles et points à vérifier avant de choisir cette icône.',
  canonical:'/modeles/alessi-9090/',
  body:wrap('Alessi 9090 : design Richard Sapper, inox et induction','La 9090 n’est pas seulement une moka chère et dessinée : sa base élargie, son bec anti-goutte et sa fermeture à levier font partie du projet depuis son lancement.','Modèle · Alessi',`
<section class="guide-answer"><span class="eyebrow">Verdict documentaire</span><h2>Le surcoût achète surtout une conception particulière, pas une promesse de meilleur café</h2><p>Dessinée par Richard Sapper et produite depuis 1980, la 9090 combine inox 18/10, fond magnétique pour l’induction et plusieurs choix fonctionnels inhabituels : base élargie, bec anti-goutte et fermeture à levier.</p><p>Elle a donc du sens si vous valorisez réellement ces choix de conception et la fabrication de l’objet. Si votre priorité est uniquement de préparer une moka sur induction au coût le plus rationnel, des alternatives Bialetti seront plus directes.</p></section>
<section><h2>Ce qui la distingue d’une moka classique</h2><div class="guide-split"><div><h3>Fermeture à levier</h3><p>Alessi remplace la fermeture vissée classique par un mécanisme à levier permettant d’ouvrir la cafetière d’un geste.</p></div><div><h3>Base élargie</h3><p>Le dessin cherche aussi à améliorer la stabilité et l’exploitation de la chaleur, pas seulement à produire une silhouette reconnaissable.</p></div><div><h3>Bec anti-goutte</h3><p>Le bec fait partie des innovations fonctionnelles explicitement documentées par Alessi.</p></div><div><h3>Inox 18/10</h3><p>La construction la place dans un univers matériel différent des moka classiques en fonte d’aluminium.</p></div></div></section>
<section><h2>Induction : même la petite 9090 demande une vérification</h2><p>La référence 1 tasse est donnée pour <strong>7 cl</strong>, avec un diamètre de <strong>9,5 cm</strong>. Alessi demande explicitement de vérifier que la plaque induction peut s’activer avec un objet d’au moins <strong>90 mm</strong> de diamètre. C’est un bon exemple de la différence entre “fond magnétique” et “détection garantie sur toute plaque”.</p><p>La gamme actuelle affiche également des versions 3, 6 et 10 tasses. Vérifiez toujours la référence exacte avant achat.</p></section>
<section><h2>Pour qui la 9090 est cohérente</h2><p>Elle vise le lecteur pour qui l’objet de cuisine compte autant que sa fonction : matériau, mécanique d’ouverture, histoire du design et fabrication. Elle est moins rationnelle si vous cherchez uniquement l’option induction la plus simple ou la moins chère.</p><p><a class="text-link" href="/marques/alessi/">Comprendre la gamme Alessi</a> · <a class="text-link" href="/comparatifs/cafetiere-italienne-design/">Comparer les moka design</a> · <a class="text-link" href="/comparatifs/cafetiere-italienne-inox/">Comparer les moka inox</a></p></section>
<section id="sources"><h2>Sources vérifiées</h2><ul class="source-list"><li><a href="https://alessi.com/products/9090-espresso-coffee-maker">Alessi — 9090</a></li><li><a href="https://ch.alessi.com/fr/products/9090-espresso-coffee-maker">Alessi — 9090, fiche française</a></li></ul></section>`,`<h3>À retenir</h3><p>Inox 18/10, levier, bec anti-goutte, induction ; sur la 1 tasse, vérifiez la détection minimale de votre plaque.</p><span class="pill">Richard Sapper</span><span class="pill">Inox</span>`)
 }
};